"""agy-seo: 1-Click Remediation Engine — Auto-generates fix files.

Generates ready-to-use remediation assets:
- sitemap.xml based on crawled pages
- robots.txt optimized for SEO + AI search
- schema.json (per-page JSON-LD based on page type detection)
- llms.txt and llms-full.txt for AI search optimization
"""

import json
import os
from datetime import datetime
from urllib.parse import urlparse
from utils import normalize_url


def generate_sitemap_xml(all_pages: dict, base_url: str) -> str:
    """Generate a complete XML sitemap from crawled pages.
    
    Args:
        all_pages: Dict of {norm_url: page_info} from the crawler
        base_url: The base URL of the site
    
    Returns:
        Complete sitemap.xml content as string
    """
    today = datetime.now().strftime("%Y-%m-%d")
    
    urls = []
    for norm_url, page_info in all_pages.items():
        if not page_info.get("parsed"):
            continue
        
        page_url = page_info["parsed"].get("url", norm_url)
        
        # Determine priority based on URL depth
        path = urlparse(page_url).path
        depth = len([p for p in path.split("/") if p])
        
        if depth == 0:  # Homepage
            priority = "1.0"
            changefreq = "daily"
        elif depth == 1:  # Top-level pages
            priority = "0.8"
            changefreq = "weekly"
        elif depth == 2:  # Sub-pages
            priority = "0.6"
            changefreq = "weekly"
        else:  # Deep pages
            priority = "0.4"
            changefreq = "monthly"
        
        urls.append({
            "loc": page_url,
            "lastmod": today,
            "changefreq": changefreq,
            "priority": priority,
        })
    
    # Sort: homepage first, then by priority descending
    urls.sort(key=lambda u: (-float(u["priority"]), u["loc"]))
    
    xml_lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ]
    
    for u in urls:
        xml_lines.append("  <url>")
        xml_lines.append(f"    <loc>{_escape_xml(u['loc'])}</loc>")
        xml_lines.append(f"    <lastmod>{u['lastmod']}</lastmod>")
        xml_lines.append(f"    <changefreq>{u['changefreq']}</changefreq>")
        xml_lines.append(f"    <priority>{u['priority']}</priority>")
        xml_lines.append("  </url>")
    
    xml_lines.append("</urlset>")
    
    return "\n".join(xml_lines)


def generate_robots_txt(base_url: str, has_sitemap: bool = True,
                         block_training_bots: bool = True) -> str:
    """Generate an optimized robots.txt file.
    
    Args:
        base_url: The base URL of the site
        has_sitemap: Whether to include sitemap declaration
        block_training_bots: Whether to block AI training-only bots
    
    Returns:
        Complete robots.txt content as string
    """
    lines = [
        "# ============================================",
        f"# robots.txt for {urlparse(base_url).netloc}",
        f"# Generated by InersiaLab SEO Audit Engine",
        f"# Date: {datetime.now().strftime('%Y-%m-%d')}",
        "# ============================================",
        "",
        "# Allow all standard search engines",
        "User-agent: *",
        "Allow: /",
        "",
        "# Block common non-content paths",
        "Disallow: /wp-admin/",
        "Disallow: /wp-includes/",
        "Disallow: /wp-json/",
        "Disallow: /cgi-bin/",
        "Disallow: /tmp/",
        "Disallow: /*.json$",
        "Disallow: /search",
        "Disallow: /*?s=",
        "Disallow: /*?p=",
        "Disallow: /tag/",
        "",
        "# Allow CSS/JS for rendering",
        "Allow: /wp-content/uploads/",
        "Allow: /wp-content/themes/",
        "Allow: /wp-content/plugins/",
        "Allow: /*.css$",
        "Allow: /*.js$",
        "",
        "# ============================================",
        "# AI Search Engine Bots (ALLOW for visibility)",
        "# ============================================",
        "",
        "# OpenAI Search (ChatGPT Search results)",
        "User-agent: OAI-SearchBot",
        "Allow: /",
        "",
        "# ChatGPT Browsing",
        "User-agent: ChatGPT-User",
        "Allow: /",
        "",
        "# Perplexity Search",
        "User-agent: PerplexityBot",
        "Allow: /",
        "",
        "# Anthropic Claude Search",
        "User-agent: Claude-SearchBot",
        "Allow: /",
        "",
    ]
    
    if block_training_bots:
        lines.extend([
            "# ============================================",
            "# AI Training Bots (BLOCK to protect content)",
            "# ============================================",
            "",
            "# OpenAI Training",
            "User-agent: GPTBot",
            "Disallow: /",
            "",
            "# Anthropic Training",
            "User-agent: ClaudeBot",
            "Disallow: /",
            "",
            "# Google Gemini Training",
            "User-agent: Google-Extended",
            "Disallow: /",
            "",
            "# Apple Intelligence Training",
            "User-agent: Applebot-Extended",
            "Disallow: /",
            "",
            "# Common Crawl",
            "User-agent: CCBot",
            "Disallow: /",
            "",
            "# ByteDance / TikTok",
            "User-agent: Bytespider",
            "Disallow: /",
            "",
        ])
    
    if has_sitemap:
        lines.extend([
            "# ============================================",
            "# Sitemap",
            "# ============================================",
            f"Sitemap: {base_url.rstrip('/')}/sitemap.xml",
            "",
        ])
    
    return "\n".join(lines)


def _detect_page_type(page_data: dict) -> str:
    """Detect the type of page based on content and URL analysis."""
    url = page_data.get("url", "").lower()
    title = page_data.get("title", "").lower()
    schema = page_data.get("schema", [])
    word_count = page_data.get("word_count", 0)
    forms = page_data.get("forms", [])
    path = urlparse(url).path.lower()
    
    # Check existing schema types
    schema_types = set()
    for s in schema:
        if isinstance(s, dict):
            st = s.get("@type", "")
            if isinstance(st, list):
                schema_types.update(st)
            else:
                schema_types.add(st)
    
    # Homepage
    if path in ("/", ""):
        return "homepage"
    
    # Contact page
    if any(k in path for k in ["/contact", "/iletisim", "/تواصل"]):
        return "contact"
    
    # About page
    if any(k in path for k in ["/about", "/hakkimizda", "/من-نحن"]):
        return "about"
    
    # Blog/Article
    if any(k in path for k in ["/blog", "/article", "/post", "/news", "/مقال"]):
        return "article"
    if "Article" in schema_types or "BlogPosting" in schema_types:
        return "article"
    
    # Service page
    if any(k in path for k in ["/service", "/hizmet", "/خدمات", "/خدمة"]):
        return "service"
    if "Service" in schema_types:
        return "service"
    
    # Product page
    if any(k in path for k in ["/product", "/urun", "/منتج"]):
        return "product"
    if "Product" in schema_types:
        return "product"
    
    # FAQ page
    if any(k in path for k in ["/faq", "/sss", "/الأسئلة"]):
        return "faq"
    if "FAQPage" in schema_types:
        return "faq"
    
    # Medical/health
    if any(k in path for k in ["/treatment", "/tedavi", "/علاج", "/doctor", "/doktor"]):
        return "medical"
    if any(t in schema_types for t in ("MedicalClinic", "MedicalOrganization", "Hospital", "Physician")):
        return "medical"
    
    # Default: generic webpage
    return "webpage"


def generate_schema_json(page_data: dict, base_url: str) -> dict:
    """Generate appropriate JSON-LD schema for a page based on type detection.
    
    Returns a complete, ready-to-use JSON-LD object.
    """
    page_type = _detect_page_type(page_data)
    url = page_data.get("url", base_url)
    title = page_data.get("title", "")
    description = page_data.get("meta_description", "")
    domain = urlparse(url).netloc
    today = datetime.now().strftime("%Y-%m-%dT%H:%M:%SZ")
    
    # Base organization info
    org_name = domain.split(".")[0].title()
    existing_schema = page_data.get("schema", [])
    for s in existing_schema:
        if isinstance(s, dict) and s.get("@type") in ("Organization", "LocalBusiness"):
            org_name = s.get("name", org_name)
    
    schemas = []
    
    # Always include WebSite schema for homepage
    if page_type == "homepage":
        schemas.append({
            "@context": "https://schema.org",
            "@type": "WebSite",
            "name": org_name,
            "url": base_url,
            "potentialAction": {
                "@type": "SearchAction",
                "target": f"{base_url.rstrip('/')}/search?q={{search_term_string}}",
                "query-input": "required name=search_term_string",
            },
        })
        schemas.append({
            "@context": "https://schema.org",
            "@type": "Organization",
            "name": org_name,
            "url": base_url,
            "logo": f"{base_url.rstrip('/')}/logo.png",
            "sameAs": [
                "https://www.linkedin.com/company/YOURCOMPANY",
                "https://twitter.com/YOURHANDLE",
            ],
            "contactPoint": {
                "@type": "ContactPoint",
                "contactType": "customer service",
                "availableLanguage": ["English"],
            },
        })
    
    elif page_type == "article":
        schemas.append({
            "@context": "https://schema.org",
            "@type": "Article",
            "headline": title,
            "description": description,
            "url": url,
            "datePublished": today,
            "dateModified": today,
            "author": {
                "@type": "Organization",
                "name": org_name,
            },
            "publisher": {
                "@type": "Organization",
                "name": org_name,
                "logo": {
                    "@type": "ImageObject",
                    "url": f"{base_url.rstrip('/')}/logo.png",
                },
            },
            "mainEntityOfPage": url,
        })
    
    elif page_type == "service":
        schemas.append({
            "@context": "https://schema.org",
            "@type": "Service",
            "name": title,
            "description": description,
            "url": url,
            "provider": {
                "@type": "Organization",
                "name": org_name,
                "url": base_url,
            },
            "areaServed": {
                "@type": "Country",
                "name": "YOUR_COUNTRY",
            },
        })
    
    elif page_type == "product":
        schemas.append({
            "@context": "https://schema.org",
            "@type": "Product",
            "name": title,
            "description": description,
            "url": url,
            "brand": {
                "@type": "Brand",
                "name": org_name,
            },
            "offers": {
                "@type": "Offer",
                "priceCurrency": "USD",
                "price": "0.00",
                "availability": "https://schema.org/InStock",
            },
        })
    
    elif page_type == "contact":
        schemas.append({
            "@context": "https://schema.org",
            "@type": "ContactPage",
            "name": title or "Contact Us",
            "description": description or f"Contact {org_name}",
            "url": url,
            "mainEntity": {
                "@type": "Organization",
                "name": org_name,
                "url": base_url,
                "contactPoint": {
                    "@type": "ContactPoint",
                    "contactType": "customer service",
                    "availableLanguage": ["English"],
                },
            },
        })
    
    elif page_type == "about":
        schemas.append({
            "@context": "https://schema.org",
            "@type": "AboutPage",
            "name": title or f"About {org_name}",
            "description": description,
            "url": url,
            "mainEntity": {
                "@type": "Organization",
                "name": org_name,
                "url": base_url,
                "foundingDate": "YYYY",
                "description": description,
            },
        })
    
    elif page_type == "faq":
        # Extract Q&A from headings
        h2s = page_data.get("h2", [])
        h3s = page_data.get("h3", [])
        questions = [h for h in h2s + h3s if h.strip().endswith("?")]
        
        faq_entities = []
        for q in questions[:10]:
            faq_entities.append({
                "@type": "Question",
                "name": q,
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": f"[Add answer for: {q}]",
                },
            })
        
        if faq_entities:
            schemas.append({
                "@context": "https://schema.org",
                "@type": "FAQPage",
                "mainEntity": faq_entities,
            })
    
    elif page_type == "medical":
        schemas.append({
            "@context": "https://schema.org",
            "@type": "MedicalWebPage",
            "name": title,
            "description": description,
            "url": url,
            "about": {
                "@type": "MedicalCondition",
                "name": title,
            },
            "lastReviewed": today,
        })
    
    else:  # Generic webpage
        schemas.append({
            "@context": "https://schema.org",
            "@type": "WebPage",
            "name": title,
            "description": description,
            "url": url,
            "isPartOf": {
                "@type": "WebSite",
                "name": org_name,
                "url": base_url,
            },
        })
    
    # Always add BreadcrumbList for non-homepage pages
    if page_type != "homepage":
        path_parts = [p for p in urlparse(url).path.split("/") if p]
        breadcrumb_items = [{
            "@type": "ListItem",
            "position": 1,
            "name": "Home",
            "item": base_url,
        }]
        cumulative_path = base_url.rstrip("/")
        for i, part in enumerate(path_parts, start=2):
            cumulative_path += f"/{part}"
            breadcrumb_items.append({
                "@type": "ListItem",
                "position": i,
                "name": part.replace("-", " ").replace("_", " ").title(),
                "item": cumulative_path,
            })
        
        schemas.append({
            "@context": "https://schema.org",
            "@type": "BreadcrumbList",
            "itemListElement": breadcrumb_items,
        })
    
    return {
        "page_type": page_type,
        "schemas": schemas,
        "html_snippet": _schemas_to_html(schemas),
    }


def _schemas_to_html(schemas: list) -> str:
    """Convert schema list to HTML script tags."""
    snippets = []
    for s in schemas:
        json_str = json.dumps(s, indent=2, ensure_ascii=False)
        snippets.append(f'<script type="application/ld+json">\n{json_str}\n</script>')
    return "\n\n".join(snippets)


def _escape_xml(text: str) -> str:
    """Escape special XML characters."""
    return (text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
            .replace("'", "&apos;"))


def generate_all_remediation_files(audit_result: dict, output_dir: str) -> dict:
    """Generate all remediation files and save to output directory.
    
    Args:
        audit_result: Complete audit result dict from run_audit()
        output_dir: Directory to save generated files
    
    Returns:
        Dict of {filename: filepath} for all generated files
    """
    os.makedirs(output_dir, exist_ok=True)
    
    base_url = audit_result.get("base_url", "")
    all_pages = audit_result.get("_all_pages", {})  # Raw page data from crawler
    page_results = audit_result.get("page_results", {})
    
    generated_files = {}
    
    # 1. sitemap.xml
    if all_pages:
        sitemap_content = generate_sitemap_xml(all_pages, base_url)
        sitemap_path = os.path.join(output_dir, "sitemap.xml")
        with open(sitemap_path, "w", encoding="utf-8") as f:
            f.write(sitemap_content)
        generated_files["sitemap.xml"] = sitemap_path
    
    # 2. robots.txt
    robots_content = generate_robots_txt(base_url)
    robots_path = os.path.join(output_dir, "robots.txt")
    with open(robots_path, "w", encoding="utf-8") as f:
        f.write(robots_content)
    generated_files["robots.txt"] = robots_path
    
    # 3. Schema JSON for each page
    schema_dir = os.path.join(output_dir, "schema")
    os.makedirs(schema_dir, exist_ok=True)
    
    for page_url, results in page_results.items():
        # Get the parsed page data
        page_data_for_schema = None
        for norm_url, page_info in all_pages.items():
            if page_info.get("parsed", {}).get("url") == page_url:
                page_data_for_schema = page_info["parsed"]
                break
        
        if not page_data_for_schema:
            continue
        
        schema_result = generate_schema_json(page_data_for_schema, base_url)
        
        # Create safe filename
        path = urlparse(page_url).path.strip("/").replace("/", "_") or "homepage"
        safe_name = "".join(c if c.isalnum() or c in "_-" else "_" for c in path)[:60]
        
        schema_file = os.path.join(schema_dir, f"{safe_name}_schema.json")
        with open(schema_file, "w", encoding="utf-8") as f:
            json.dump(schema_result["schemas"], f, indent=2, ensure_ascii=False)
        generated_files[f"schema/{safe_name}_schema.json"] = schema_file
        
        # Also save the HTML snippet
        snippet_file = os.path.join(schema_dir, f"{safe_name}_schema.html")
        with open(snippet_file, "w", encoding="utf-8") as f:
            f.write(f"<!-- JSON-LD Schema for: {page_url} -->\n")
            f.write(f"<!-- Page type: {schema_result['page_type']} -->\n\n")
            f.write(schema_result["html_snippet"])
        generated_files[f"schema/{safe_name}_schema.html"] = snippet_file
    
    # 4. llms.txt
    geo_data = None
    for page_url, results in page_results.items():
        geo_result = results.get("ai_search_geo", {})
        if geo_result.get("generated_llms_txt"):
            geo_data = geo_result
            break
    
    if geo_data:
        llms_path = os.path.join(output_dir, "llms.txt")
        with open(llms_path, "w", encoding="utf-8") as f:
            f.write(geo_data["generated_llms_txt"])
        generated_files["llms.txt"] = llms_path
        
        if geo_data.get("generated_llms_full_txt"):
            llms_full_path = os.path.join(output_dir, "llms-full.txt")
            with open(llms_full_path, "w", encoding="utf-8") as f:
                f.write(geo_data["generated_llms_full_txt"])
            generated_files["llms-full.txt"] = llms_full_path
    
    return generated_files
