"""agy-seo: Executive HTML Report Builder & Playwright PDF Renderer.

Presents all SEO audit findings directly in a clean, professional Table Format:
- Column 1: Problem / Defect (Category, Severity, Issue name, Location, Diagnostic Detail)
- Column 2: Solution / Fix (Actionable implementation instructions and copy-paste code)
- Strict 3-color palette: Black (text/borders), Red (problems), Green (solutions).
- No icons/emojis, no box shadows, pure white background.
- Official attribution: 'Report generated by the Software Department of InersiaLab'.
"""

import html
import json
import os
import re
import sys
from datetime import datetime
from urllib.parse import urlparse, unquote

if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass


# ---------------------------------------------------------------------------
# Strict 3-Color Scheme & Professional Severity Labels
# ---------------------------------------------------------------------------

COLOR_BLACK = "#111827"
COLOR_RED = "#b91c1c"
COLOR_GREEN = "#15803d"
COLOR_MUTED = "#4b5563"
COLOR_BORDER = "#e5e7eb"

SEVERITY_TEXT_COLORS = {
    "critical": COLOR_RED,
    "high": COLOR_RED,
    "medium": COLOR_RED,
    "low": COLOR_BLACK,
    "info": COLOR_MUTED,
}

SEVERITY_LABELS = {
    "critical": "[CRITICAL DEFECT]",
    "high": "[HIGH PRIORITY]",
    "medium": "[MEDIUM PRIORITY]",
    "low": "[LOW PRIORITY]",
    "info": "[INFORMATIONAL NOTE]",
}


def score_color(score: int) -> str:
    """Returns Red for poor/failing scores, Green for strong/good scores, Black for neutral."""
    if score >= 85:
        return COLOR_GREEN
    elif score >= 70:
        return COLOR_BLACK
    return COLOR_RED


def score_grade(score: int) -> str:
    if score >= 90: return "A"
    if score >= 80: return "B"
    if score >= 70: return "C"
    if score >= 60: return "D"
    return "F"


# ---------------------------------------------------------------------------
# Intelligent Finding & Fix Pairing Engine
# ---------------------------------------------------------------------------

def _pair_finding_with_solution(finding: dict, available_fixes: list) -> dict:
    """Matches a finding with its corresponding fix or generates an accurate fallback solution."""
    issue_lower = finding.get("issue", "").lower()
    cat_lower = finding.get("category", "").lower()

    # 1. Exact match first
    for fix in available_fixes:
        fix_issue_lower = fix.get("issue", "").lower()
        if fix_issue_lower == issue_lower:
            return fix

    # 2. Specific keyword direct matching
    SPECIFIC_KEYWORDS = [
        "orphan", "anchor", "broken", "nofollow", "redirect", "sitemap",
        "robots.txt", "schema", "json-ld", "h1", "title", "meta description",
        "ttfb", "cls", "lcp", "render-blocking", "dimensions", "lazy",
        "crawler", "searchgpt", "perplexity", "llms.txt", "freshness", "thin",
        "security", "https", "canonical"
    ]
    for kw in SPECIFIC_KEYWORDS:
        if kw in issue_lower or kw in cat_lower:
            for fix in available_fixes:
                if kw in fix.get("issue", "").lower():
                    return fix

    # 3. Substring match
    for fix in available_fixes:
        fix_issue_lower = fix.get("issue", "").lower()
        if fix_issue_lower in issue_lower or issue_lower in fix_issue_lower:
            return fix

    # 4. Significant non-generic word overlap (exclude common stop words)
    STOP_WORDS = {"links", "link", "page", "pages", "site", "found", "using", "with", "from", "causes", "other", "than"}
    issue_words = [w for w in re.findall(r'\b\w{4,}\b', issue_lower) if w not in STOP_WORDS]
    best_fix = None
    max_overlap = 0
    for fix in available_fixes:
        fix_words = set(re.findall(r'\b\w{4,}\b', fix.get("issue", "").lower()))
        overlap = len(fix_words.intersection(issue_words))
        if overlap > max_overlap:
            max_overlap = overlap
            best_fix = fix

    if best_fix and max_overlap > 0:
        return best_fix

    # 5. Comprehensive fallback solution generation if no explicit fix was returned
    return {
        "issue": finding.get("issue", "Remediation Action"),
        "fix": _generate_fallback_solution(finding),
    }


def _generate_fallback_solution(finding: dict) -> str:
    """Generates concrete, copy-paste remediation steps based on the finding category and issue."""
    issue = finding.get("issue", "").lower()
    cat = finding.get("category", "").lower()
    detail = finding.get("detail", "")

    if "orphan" in issue or "orphan" in cat:
        return (
            "Add internal contextual links to this orphan page from relevant category and parent pages:\n"
            "1. Identify 2-3 topically related parent or pillar pages\n"
            "2. Add contextual in-body links using descriptive anchor text\n"
            "3. Ensure the page is included in the XML sitemap"
        )
    elif "broken" in issue or "broken" in cat:
        return (
            "Inspect and repair or remove broken outbound hyperlinks:\n"
            "1. Replace dead social sharing links with active standard widget links\n"
            "2. Update outdated external references to live destinations\n"
            "3. Remove links to non-existent resources"
        )
    elif "title" in issue or "title" in cat:
        return (
            "Craft a unique, compelling <title> tag between 50-60 characters containing the primary keyword and brand name:\n\n"
            "<title>Primary Keyword &mdash; Secondary Service | Brand Name</title>\n\n"
            "Ensure the title accurately reflects the main page topic and avoids keyword stuffing."
        )
    elif "meta description" in issue or "meta description" in cat:
        return (
            "Add a concise meta description between 120-155 characters that summarizes the page and includes a call-to-action:\n\n"
            '<meta name="description" content="Discover professional solutions and services tailored to your needs. Contact our team today for a consultation." />'
        )
    elif "h1" in issue or "heading" in cat:
        return (
            "Structure headings hierarchically. Ensure exactly one semantic <h1> element is present at the top of the body:\n\n"
            "<h1>Descriptive Primary Topic Heading</h1>\n\n"
            "Convert any duplicate or secondary <h1> elements into <h2> or <h3> subheadings."
        )
    elif "sitemap" in issue or "sitemap" in cat:
        return (
            "Generate and publish an XML sitemap declaring all canonical indexable pages:\n"
            "1. Place the generated file at domain root: /sitemap.xml\n"
            "2. Reference the sitemap inside robots.txt:\n"
            "   Sitemap: https://yourdomain.com/sitemap.xml\n"
            "3. Submit the sitemap in Google Search Console under 'Sitemaps'."
        )
    elif "robots.txt" in issue or "crawlability" in cat:
        return (
            "Create or correct the robots.txt file at domain root:\n\n"
            "User-agent: *\n"
            "Allow: /\n\n"
            "Sitemap: https://yourdomain.com/sitemap.xml"
        )
    elif "alt" in issue:
        return (
            "Provide concise, descriptive alt attributes for all <img> tags to ensure search indexing and accessibility:\n\n"
            '<img src="example.jpg" alt="Clear description of the visual content and context" />\n\n'
            'For purely decorative images, set an empty alt attribute: alt=""'
        )
    elif "width" in issue or "height" in issue or "cls" in issue:
        return (
            "Specify explicit width and height dimensions on all image tags to prevent Cumulative Layout Shift (CLS):\n\n"
            '<img src="example.jpg" width="800" height="600" alt="Description" />\n\n'
            "Alternatively, reserve space in CSS: img { aspect-ratio: 16/9; width: 100%; height: auto; }"
        )
    elif "schema" in issue or "structured data" in cat:
        return (
            "Implement Schema.org JSON-LD structured data in the document <head>:\n\n"
            '<script type="application/ld+json">\n'
            "{\n"
            '  "@context": "https://schema.org",\n'
            '  "@type": "WebPage",\n'
            '  "name": "Page Title",\n'
            '  "url": "https://yourdomain.com/page"\n'
            "}\n"
            "</script>"
        )
    elif "security" in issue or "https" in issue:
        return (
            "Configure modern security headers in your web server (Apache/Nginx/Cloudflare):\n\n"
            "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload\n"
            "X-Content-Type-Options: nosniff\n"
            "X-Frame-Options: SAMEORIGIN\n"
            "Referrer-Policy: strict-origin-when-cross-origin"
        )
    elif "render-blocking" in issue or "render blocking" in issue:
        return (
            "Defer non-critical external JavaScript files so HTML parsing can complete without interruption:\n\n"
            '<script src="bundle.js" defer></script>\n\n'
            "For non-critical stylesheets, load asynchronously using rel='preload' or media='print'."
        )
    elif "ttfb" in issue:
        return (
            "Reduce server response latency (TTFB):\n"
            "1. Implement server-side caching (Redis, Varnish, or CMS cache)\n"
            "2. Route traffic through a global CDN (e.g. Cloudflare)\n"
            "3. Optimize database queries and slow PHP/Node.js backend execution"
        )
    elif "ai" in issue or "bot" in issue or "geo" in cat:
        return (
            "Optimize for Generative Search Engines (SearchGPT, Perplexity, Claude):\n"
            "1. Allow AI search bots in robots.txt:\n"
            "   User-agent: OAI-SearchBot\n   Allow: /\n   User-agent: PerplexityBot\n   Allow: /\n"
            "2. Publish /llms.txt at domain root containing a clean markdown summary of core services."
        )
    elif "thin" in issue or "word count" in issue:
        return (
            "Expand textual content to at least 350-500 words of comprehensive, original material "
            "addressing the user's primary search intent and topic questions."
        )
    elif "internal link" in issue:
        return (
            "Add contextual internal links within body copy connecting this page to related service "
            "and category pages to distribute link equity and assist crawlers."
        )
    else:
        return (
            "Review the diagnostic detail and implement corrective code adhering to Google Search Essentials "
            "and W3C web standards."
        )


def _filter_items_by_category(items: list, category_key: str) -> list:
    """Filter paired problem-solution items strictly by audit discipline."""
    cat_key = category_key.lower().strip()
    matched = []

    for item in items:
        an = item.get("analyzer", "").lower()
        f = item.get("finding", {})
        issue = f.get("issue", "").lower()
        cat = f.get("category", "").lower()

        if cat_key == "technical":
            if an in ("technical", "robots & sitemaps") or "technical" in an or "robots" in an or "sitemap" in an or cat in ("technical", "security", "infrastructure"):
                matched.append(item)
            elif an == "cross-page patterns" and not any(w in issue for w in ("title", "description", "orphan")):
                matched.append(item)
        elif cat_key == "onpage":
            if an in ("on_page", "onpage") or "on_page" in an or cat in ("on-page", "onpage", "meta", "headings"):
                matched.append(item)
            elif an == "cross-page patterns" and any(w in issue for w in ("title", "description")):
                matched.append(item)
        elif cat_key == "geo":
            if an in ("ai_search_geo", "geo") or "geo" in an or "ai" in an or cat in ("geo", "ai search", "generative seo"):
                matched.append(item)
        elif cat_key == "content":
            if an in ("content_quality", "content") or "content" in an or cat in ("content", "e-e-a-t", "eeat"):
                matched.append(item)
        elif cat_key == "schema":
            if an in ("schema", "schema_analyzer") or "schema" in an or cat in ("schema", "structured data"):
                matched.append(item)
        elif cat_key == "performance":
            if an in ("performance",) or "performance" in an or cat in ("performance", "speed"):
                matched.append(item)
        elif cat_key == "links":
            if an in ("links",) or "link" in an or cat in ("links", "internal links"):
                matched.append(item)
            elif an == "cross-page patterns" and "orphan" in issue:
                matched.append(item)
        elif cat_key == "images":
            if an in ("images",) or "image" in an or cat in ("images", "media"):
                matched.append(item)

    return matched


# ---------------------------------------------------------------------------
# HTML Report Builder
# ---------------------------------------------------------------------------

def build_report_html(audit_result: dict, report_mode: str = "detailed") -> str:
    """Build an executive HTML report with all results presented in Problem & Solution Tables."""
    domain = audit_result["domain"]
    base_url = audit_result["base_url"]
    pages_crawled = audit_result["pages_crawled"]
    site_scores = audit_result["site_scores"]
    overall_score = audit_result["overall_score"]
    page_results = audit_result["page_results"]
    site_findings = audit_result.get("site_findings", {})
    crawl_errors = audit_result.get("crawl_errors", [])
    timestamp = datetime.now().strftime("%B %d, %Y at %H:%M")

    # Collect and classify all findings paired with solutions
    all_paired_items = []

    # Page-level findings
    for page_url, page in page_results.items():
        for analyzer_name, result in page.items():
            if isinstance(result, dict) and "findings" in result:
                avail_fixes = result.get("fixes", [])
                for f in result["findings"]:
                    f["_page"] = page_url
                    f["_analyzer"] = analyzer_name
                    sol = _pair_finding_with_solution(f, avail_fixes)
                    all_paired_items.append({
                        "finding": f,
                        "fix": sol,
                        "page": page_url,
                        "analyzer": analyzer_name,
                    })

    # Site-level findings
    for analyzer_name, result in site_findings.items():
        if isinstance(result, dict) and "findings" in result:
            avail_fixes = result.get("fixes", [])
            for f in result["findings"]:
                f["_page"] = "Site-Wide Infrastructure"
                f["_analyzer"] = analyzer_name
                sol = _pair_finding_with_solution(f, avail_fixes)
                all_paired_items.append({
                    "finding": f,
                    "fix": sol,
                    "page": "Site-Wide Infrastructure",
                    "analyzer": analyzer_name,
                })

    # Count issues by severity
    severity_counts = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
    for item in all_paired_items:
        sev = item["finding"].get("severity", "info").lower()
        severity_counts[sev] = severity_counts.get(sev, 0) + 1

    total_issues = sum(v for k, v in severity_counts.items() if k != "info")

    # Score retrieval helper
    def _cat_score(*keys) -> int:
        for k in keys:
            if k in site_scores:
                return site_scores[k]
            for sk, sv in site_scores.items():
                if sk.lower() == k.lower():
                    return sv
        return 0

    tech_score = _cat_score("Technical", "Robots & Sitemaps")
    onpage_score = _cat_score("On Page")
    geo_score = _cat_score("Ai Search Geo", "Geo")
    content_score = _cat_score("Content Quality", "Content")
    schema_score = _cat_score("Schema")
    perf_score = _cat_score("Performance")
    links_score = _cat_score("Links")
    images_score = _cat_score("Images")

    tech_items = _filter_items_by_category(all_paired_items, "technical")
    onpage_items = _filter_items_by_category(all_paired_items, "onpage")
    geo_items = _filter_items_by_category(all_paired_items, "geo")
    content_items = _filter_items_by_category(all_paired_items, "content")
    schema_items = _filter_items_by_category(all_paired_items, "schema")
    perf_items = _filter_items_by_category(all_paired_items, "performance")
    link_items = _filter_items_by_category(all_paired_items, "links")
    image_items = _filter_items_by_category(all_paired_items, "images")

    mode_label = "Executive Summary &amp; Strategic Remediation Report" if report_mode == "short" else "Comprehensive Technical &amp; Generative SEO Audit"
    subtitle_text = f"{mode_label} &bull; Report generated by the Software Department of InersiaLab"

    parts = []
    parts.append(_css())
    parts.append(f"""
    <div class="report-container">
        <!-- COVER PAGE -->
        <div class="cover-page">
            <div class="header-rule"></div>
            <div class="organization-tag">INERSIALAB SOFTWARE DEPARTMENT</div>
            <h1 class="report-main-title">{mode_label}</h1>
            <div class="report-subtitle">{subtitle_text}</div>

            <div class="meta-block">
                <table class="meta-table">
                    <tr>
                        <td class="meta-label">Target Domain:</td>
                        <td class="meta-value"><strong>{_e(domain)}</strong></td>
                    </tr>
                    <tr>
                        <td class="meta-label">Target URL:</td>
                        <td class="meta-value">{_e(base_url)}</td>
                    </tr>
                    <tr>
                        <td class="meta-label">Audit Date:</td>
                        <td class="meta-value">{timestamp}</td>
                    </tr>
                    <tr>
                        <td class="meta-label">Pages Inspected:</td>
                        <td class="meta-value">{pages_crawled}</td>
                    </tr>
                    <tr>
                        <td class="meta-label">Report Format:</td>
                        <td class="meta-value"><strong>{report_mode.upper()}</strong></td>
                    </tr>
                </table>
            </div>

            <div class="kpi-summary-grid">
                <div class="kpi-box">
                    <div class="kpi-number" style="color: {score_color(overall_score)};">{overall_score}/100</div>
                    <div class="kpi-title">Overall Score (Grade {score_grade(overall_score)})</div>
                </div>
                <div class="kpi-box">
                    <div class="kpi-number" style="color: {COLOR_RED if severity_counts['critical'] > 0 else COLOR_BLACK};">{severity_counts['critical']}</div>
                    <div class="kpi-title">Critical Defects</div>
                </div>
                <div class="kpi-box">
                    <div class="kpi-number" style="color: {COLOR_RED if severity_counts['high'] > 0 else COLOR_BLACK};">{severity_counts['high']}</div>
                    <div class="kpi-title">High Priority Defects</div>
                </div>
                <div class="kpi-box">
                    <div class="kpi-number" style="color: {COLOR_BLACK};">{total_issues}</div>
                    <div class="kpi-title">Total Issues Identified</div>
                </div>
            </div>

            <div class="cover-footer">
                Report generated by the Software Department of InersiaLab &bull; All Rights Reserved
            </div>
        </div>

        <!-- TABLE OF CONTENTS / REPORT MENU -->
        <div class="section-container" id="toc">
            <div class="section-header">
                <h2>Table of Contents &amp; Report Navigation</h2>
            </div>
            <p class="section-description">
                Interactive navigation directory for all audit sections, analytical deep-dives, and remediation assets.
            </p>
            <table class="data-table toc-table">
                <thead>
                    <tr>
                        <th style="width: 60px; text-align: center;">Section</th>
                        <th>Audit Discipline &amp; Analytical Focus</th>
                        <th style="width: 100px; text-align: center;">Score</th>
                        <th style="width: 80px; text-align: center;">Action</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="text-align: center; font-weight: 700;">01</td>
                        <td><strong>Executive Summary &amp; Category Breakdown</strong><br><span style="color: #4b5563; font-size: 7.5pt;">KPI overview, overall health score, severity distributions</span></td>
                        <td style="text-align: center; font-weight: 700; color: {score_color(overall_score)};">{overall_score}/100</td>
                        <td style="text-align: center;"><a href="#section-1" class="toc-link">Jump &rarr;</a></td>
                    </tr>
                    <tr>
                        <td style="text-align: center; font-weight: 700;">02</td>
                        <td><strong>Technical &amp; Infrastructure SEO</strong><br><span style="color: #4b5563; font-size: 7.5pt;">Robots.txt, XML sitemaps, HTTP status codes, security headers</span></td>
                        <td style="text-align: center; font-weight: 700; color: {score_color(tech_score)};">{tech_score}/100</td>
                        <td style="text-align: center;"><a href="#section-2" class="toc-link">Jump &rarr;</a></td>
                    </tr>
                    <tr>
                        <td style="text-align: center; font-weight: 700;">03</td>
                        <td><strong>On-Page SEO &amp; Metadata Architecture</strong><br><span style="color: #4b5563; font-size: 7.5pt;">Title tags, meta descriptions, H1-H6 hierarchy, Open Graph</span></td>
                        <td style="text-align: center; font-weight: 700; color: {score_color(onpage_score)};">{onpage_score}/100</td>
                        <td style="text-align: center;"><a href="#section-3" class="toc-link">Jump &rarr;</a></td>
                    </tr>
                    <tr>
                        <td style="text-align: center; font-weight: 700;">04</td>
                        <td><strong>Generative Engine Optimization (GEO &amp; AI Search)</strong><br><span style="color: #4b5563; font-size: 7.5pt;">AI crawlers, LLM quotability, 5-intent AEO, llms.txt</span></td>
                        <td style="text-align: center; font-weight: 700; color: {score_color(geo_score)};">{geo_score}/100</td>
                        <td style="text-align: center;"><a href="#section-4" class="toc-link">Jump &rarr;</a></td>
                    </tr>
                    <tr>
                        <td style="text-align: center; font-weight: 700;">05</td>
                        <td><strong>Content Quality &amp; E-E-A-T Validation</strong><br><span style="color: #4b5563; font-size: 7.5pt;">Substantive copy, reading complexity, thin content detection</span></td>
                        <td style="text-align: center; font-weight: 700; color: {score_color(content_score)};">{content_score}/100</td>
                        <td style="text-align: center;"><a href="#section-5" class="toc-link">Jump &rarr;</a></td>
                    </tr>
                    <tr>
                        <td style="text-align: center; font-weight: 700;">06</td>
                        <td><strong>Schema &amp; Structured Data (JSON-LD)</strong><br><span style="color: #4b5563; font-size: 7.5pt;">JSON-LD syntax, Google Rich Snippets, entity graph</span></td>
                        <td style="text-align: center; font-weight: 700; color: {score_color(schema_score)};">{schema_score}/100</td>
                        <td style="text-align: center;"><a href="#section-6" class="toc-link">Jump &rarr;</a></td>
                    </tr>
                    <tr>
                        <td style="text-align: center; font-weight: 700;">07</td>
                        <td><strong>Performance &amp; Core Web Vitals</strong><br><span style="color: #4b5563; font-size: 7.5pt;">TTFB response latency, DOM depth, render-blocking scripts</span></td>
                        <td style="text-align: center; font-weight: 700; color: {score_color(perf_score)};">{perf_score}/100</td>
                        <td style="text-align: center;"><a href="#section-7" class="toc-link">Jump &rarr;</a></td>
                    </tr>
                    <tr>
                        <td style="text-align: center; font-weight: 700;">08</td>
                        <td><strong>Link Architecture &amp; Internal Equity</strong><br><span style="color: #4b5563; font-size: 7.5pt;">Internal PageRank, click-depth distribution, anchor text</span></td>
                        <td style="text-align: center; font-weight: 700; color: {score_color(links_score)};">{links_score}/100</td>
                        <td style="text-align: center;"><a href="#section-8" class="toc-link">Jump &rarr;</a></td>
                    </tr>
                    <tr>
                        <td style="text-align: center; font-weight: 700;">09</td>
                        <td><strong>Image Optimization &amp; Media Assets</strong><br><span style="color: #4b5563; font-size: 7.5pt;">Alt attributes, CLS dimension prevention, WebP/AVIF</span></td>
                        <td style="text-align: center; font-weight: 700; color: {score_color(images_score)};">{images_score}/100</td>
                        <td style="text-align: center;"><a href="#section-9" class="toc-link">Jump &rarr;</a></td>
                    </tr>
                    <tr>
                        <td style="text-align: center; font-weight: 700;">10</td>
                        <td><strong>{'All Pages Audit Summary Scorecard' if report_mode == 'short' else 'Page-by-Page Audit Breakdown'}</strong><br><span style="color: #4b5563; font-size: 7.5pt;">{'Consolidated matrix of scores across all URLs' if report_mode == 'short' else 'Granular multi-discipline scorecards for all crawled URLs'}</span></td>
                        <td style="text-align: center; font-weight: 700;">{pages_crawled} Pages</td>
                        <td style="text-align: center;"><a href="#section-10" class="toc-link">Jump &rarr;</a></td>
                    </tr>
                    <tr>
                        <td style="text-align: center; font-weight: 700;">11</td>
                        <td><strong>Prioritized Engineering Roadmap</strong><br><span style="color: #4b5563; font-size: 7.5pt;">Sequential remediation plan and action items</span></td>
                        <td style="text-align: center; font-weight: 700; color: #111827;">Action Plan</td>
                        <td style="text-align: center;"><a href="#section-roadmap" class="toc-link">Jump &rarr;</a></td>
                    </tr>
                </tbody>
            </table>
        </div>

        <!-- 1. EXECUTIVE SUMMARY -->
        <div class="section-container" id="section-1">
            <div class="section-header">
                <h2>1. Executive Summary & Category Breakdown</h2>
            </div>
            <p class="section-description">
                Evaluation across the core SEO disciplines. Scores reflect strict compliance with modern search engine 
                guidelines, crawl efficiency, structured data standards, and generative AI citability.
            </p>

            <table class="data-table">
                <thead>
                    <tr>
                        <th>Audit Category</th>
                        <th style="width: 120px; text-align: center;">Score</th>
                        <th style="width: 130px; text-align: center;">Status</th>
                        <th>Evaluation Summary</th>
                    </tr>
                </thead>
                <tbody>
    """)

    for cat_name, cat_score in site_scores.items():
        status_text = "Satisfactory" if cat_score >= 85 else ("Needs Improvement" if cat_score >= 70 else "Action Required")
        status_color = score_color(cat_score)
        summary_text = (
            "Well optimized with no major impediments detected." if cat_score >= 85
            else ("Minor issues found that require attention." if cat_score >= 70
            else "Significant compliance failures identified that directly harm performance.")
        )
        parts.append(f"""
                    <tr>
                        <td><strong>{_e(cat_name)}</strong></td>
                        <td style="text-align: center; font-weight: 700; color: {status_color};">{cat_score}/100</td>
                        <td style="text-align: center; font-weight: 600; color: {status_color};">{status_text}</td>
                        <td>{summary_text}</td>
                    </tr>
        """)

    parts.append(f"""
                </tbody>
            </table>

            <div style="margin-top: 25px;">
                <h3 class="subsection-title">Issues Summary by Severity</h3>
                <table class="data-table" style="width: 100%;">
                    <thead>
                        <tr>
                            <th style="color: {COLOR_RED};">Critical Priority</th>
                            <th style="color: {COLOR_RED};">High Priority</th>
                            <th>Medium Priority</th>
                            <th>Low Priority</th>
                            <th>Informational Notes</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr style="text-align: center; font-size: 14px; font-weight: 700;">
                            <td style="color: {COLOR_RED};">{severity_counts['critical']}</td>
                            <td style="color: {COLOR_RED};">{severity_counts['high']}</td>
                            <td>{severity_counts['medium']}</td>
                            <td>{severity_counts['low']}</td>
                            <td>{severity_counts['info']}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    """)

    # 2. TECHNICAL & INFRASTRUCTURE SEO AUDIT
    parts.append(f"""
        <div class="section-container" id="section-2">
            <div class="section-header">
                <h2>2. Technical &amp; Infrastructure SEO</h2>
                <div class="section-score-badge" style="color: {score_color(tech_score)};">Score: {tech_score}/100 (Grade {score_grade(tech_score)})</div>
            </div>
            <p class="section-description">
                Evaluation of domain-level server configurations, HTTPS security headers, HTTP status codes,
                canonical URL integrity, robots.txt crawl directives, XML sitemap validation, response compression,
                and modern HTTP/2 / HTTP/3 protocol support.
            </p>
    """)
    if report_mode == "short":
        parts.append("""
            <h3 class="subsection-title">Technical Defects &amp; Strategic Fixes Summary</h3>
        """)
        parts.append(_render_category_summary_table(tech_items))
    else:
        parts.append(_render_problem_solution_table(tech_items, show_page=True))
    parts.append("</div>")

    # 3. ON-PAGE SEO & METADATA ARCHITECTURE AUDIT
    parts.append(f"""
        <div class="section-container" id="section-3">
            <div class="section-header">
                <h2>3. On-Page SEO &amp; Metadata Architecture</h2>
                <div class="section-score-badge" style="color: {score_color(onpage_score)};">Score: {onpage_score}/100 (Grade {score_grade(onpage_score)})</div>
            </div>
            <p class="section-description">
                Inspection of HTML title tag relevance and length, meta description search-snippet appeal,
                H1&ndash;H6 heading hierarchy, Open Graph social cards, and Twitter Card metadata across all crawled URLs.
            </p>
    """)
    if report_mode == "short":
        parts.append("""
            <h3 class="subsection-title">On-Page Defects &amp; Strategic Fixes Summary</h3>
        """)
        parts.append(_render_category_summary_table(onpage_items))
    else:
        parts.append(_render_problem_solution_table(onpage_items, show_page=True))
    parts.append("</div>")

    # 4. GENERATIVE ENGINE OPTIMIZATION (GEO & AI SEARCH) AUDIT
    parts.append(f"""
        <div class="section-container" id="section-4">
            <div class="section-header">
                <h2>4. Generative Engine Optimization (GEO &amp; AI Search)</h2>
                <div class="section-score-badge" style="color: {score_color(geo_score)};">Score: {geo_score}/100 (Grade {score_grade(geo_score)})</div>
            </div>
            <p class="section-description">
                Readiness evaluation for generative AI answer engines including OpenAI SearchGPT, Perplexity AI,
                Anthropic Claude, and Google AI Overviews. Evaluates platform bot access, LLM quotability,
                conversational clarity, and search intent alignment.
            </p>
    """)

    # First page GEO data (homepage or primary landing page)
    first_geo = None
    for page_url, results in page_results.items():
        geo_data = results.get("ai_search_geo", {})
        if geo_data:
            first_geo = geo_data
            break

    if first_geo:
        # Platform readiness table
        platform_scores = first_geo.get("platform_scores", {})
        if platform_scores:
            parts.append("""
            <h3 class="subsection-title">AI Platform Readiness Scores</h3>
            <table class="data-table">
                <thead>
                    <tr>
                        <th>AI Search Platform</th>
                        <th style="width: 140px; text-align: center;">Readiness Score</th>
                        <th style="width: 140px; text-align: center;">Status</th>
                    </tr>
                </thead>
                <tbody>
            """)
            for platform, pscore in platform_scores.items():
                status = "Ready" if pscore >= 70 else ("Partial" if pscore >= 40 else "Blocked")
                parts.append(f"""
                    <tr>
                        <td><strong>{_e(platform)}</strong></td>
                        <td style="text-align: center; font-weight: 700; color: {score_color(pscore)};">{pscore}/100</td>
                        <td style="text-align: center; font-weight: 600; color: {score_color(pscore)};">{status}</td>
                    </tr>
                """)
            parts.append("</tbody></table>")

        # Quotability analysis
        quotability = first_geo.get("quotability", {})
        if quotability and quotability.get("total_count", 0) > 0:
            parts.append(f"""
            <h3 class="subsection-title">LLM Quotability &amp; Citation Analysis</h3>
            <table class="data-table">
                <thead>
                    <tr>
                        <th>Metric</th>
                        <th style="width: 200px; text-align: center;">Value</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><strong>Overall Quotability Score</strong></td>
                        <td style="text-align: center; font-weight: 700; color: {score_color(quotability.get('overall_score', 0))};">{quotability.get('overall_score', 0)}/100</td>
                    </tr>
                    <tr>
                        <td><strong>Passages Meeting Citation Threshold</strong></td>
                        <td style="text-align: center; font-weight: 700;">{quotability.get('citable_count', 0)} / {quotability.get('total_count', 0)} ({quotability.get('citable_ratio', (quotability.get('citable_count', 0) / quotability['total_count']) if quotability.get('total_count') else 0):.0%})</td>
                    </tr>
                    <tr>
                        <td><strong>Average Passage Length</strong></td>
                        <td style="text-align: center;">{quotability.get('avg_passage_words', 0)} words (ideal: 134-167)</td>
                    </tr>
                </tbody>
            </table>
            """)

        # 5-Intent AEO breakdown
        intent_data = first_geo.get("intent_analysis", {})
        if intent_data and intent_data.get("intents"):
            parts.append("""
            <h3 class="subsection-title">5-Intent AEO Matrix</h3>
            <table class="data-table">
                <thead>
                    <tr>
                        <th>Search Intent</th>
                        <th style="width: 140px; text-align: center;">Alignment Score</th>
                        <th>Observed Optimization Signals</th>
                    </tr>
                </thead>
                <tbody>
            """)
            for intent_name, intent_info in intent_data.get("intents", {}).items():
                signals = ", ".join(intent_info.get("signals", [])[:3]) or "None detected"
                iscore = intent_info.get("score", 0)
                parts.append(f"""
                    <tr>
                        <td><strong>{_e(intent_name.title())}</strong></td>
                        <td style="text-align: center; font-weight: 700; color: {score_color(iscore)};">{iscore}/100</td>
                        <td style="font-size: 8.5pt;">{_e(signals)}</td>
                    </tr>
                """)
            parts.append("</tbody></table>")

    if report_mode == "short":
        parts.append("""
            <h3 class="subsection-title" style="margin-top: 15px;">GEO Defects &amp; AI Optimization Strategy Summary</h3>
        """)
        parts.append(_render_category_summary_table(geo_items))
    else:
        parts.append("""
            <h3 class="subsection-title" style="margin-top: 15px;">GEO Defects &amp; AI Search Optimization Solutions</h3>
        """)
        parts.append(_render_problem_solution_table(geo_items, show_page=True))
    parts.append("</div>")

    # 5. CONTENT QUALITY & E-E-A-T VALIDATION AUDIT
    parts.append(f"""
        <div class="section-container" id="section-5">
            <div class="section-header">
                <h2>5. Content Quality &amp; E-E-A-T Validation</h2>
                <div class="section-score-badge" style="color: {score_color(content_score)};">Score: {content_score}/100 (Grade {score_grade(content_score)})</div>
            </div>
            <p class="section-description">
                Evaluation of substantive body copy depth, Flesch reading complexity, author attribution signals,
                citation and factual density, and thin content detection aligned with Google's Experience, Expertise,
                Authoritativeness, and Trustworthiness guidelines.
            </p>
    """)
    if report_mode == "short":
        parts.append("""
            <h3 class="subsection-title">Content &amp; E-E-A-T Defects &amp; Strategic Fixes Summary</h3>
        """)
        parts.append(_render_category_summary_table(content_items))
    else:
        parts.append(_render_problem_solution_table(content_items, show_page=True))
    parts.append("</div>")

    # 6. SCHEMA & STRUCTURED DATA (JSON-LD) AUDIT
    parts.append(f"""
        <div class="section-container" id="section-6">
            <div class="section-header">
                <h2>6. Schema &amp; Structured Data (JSON-LD)</h2>
                <div class="section-score-badge" style="color: {score_color(schema_score)};">Score: {schema_score}/100 (Grade {score_grade(schema_score)})</div>
            </div>
            <p class="section-description">
                Validation of Schema.org syntax integrity, JSON-LD script formatting, Google Rich Snippet
                eligibility (Organization, WebSite, BreadcrumbList, Article, Product, Service), and entity graph relations.
            </p>
    """)
    if report_mode == "short":
        parts.append("""
            <h3 class="subsection-title">Schema Defects &amp; Structured Data Strategy Summary</h3>
        """)
        parts.append(_render_category_summary_table(schema_items))
    else:
        parts.append(_render_problem_solution_table(schema_items, show_page=True))
    parts.append("</div>")

    # 7. PERFORMANCE & CORE WEB VITALS AUDIT
    parts.append(f"""
        <div class="section-container" id="section-7">
            <div class="section-header">
                <h2>7. Performance &amp; Core Web Vitals</h2>
                <div class="section-score-badge" style="color: {score_color(perf_score)};">Score: {perf_score}/100 (Grade {score_grade(perf_score)})</div>
            </div>
            <p class="section-description">
                Analysis of initial server response latency (Time to First Byte &ndash; TTFB), DOM tree complexity,
                render-blocking JavaScript and CSS resources, and overall page weight impacting user engagement and conversion.
            </p>
    """)
    if report_mode == "short":
        parts.append("""
            <h3 class="subsection-title">Performance Defects &amp; Acceleration Strategy Summary</h3>
        """)
        parts.append(_render_category_summary_table(perf_items))
    else:
        parts.append(_render_problem_solution_table(perf_items, show_page=True))
    parts.append("</div>")

    # 8. LINK ARCHITECTURE & INTERNAL EQUITY AUDIT
    parts.append(f"""
        <div class="section-container" id="section-8">
            <div class="section-header">
                <h2>8. Link Architecture &amp; Internal Equity</h2>
                <div class="section-score-badge" style="color: {score_color(links_score)};">Score: {links_score}/100 (Grade {score_grade(links_score)})</div>
            </div>
            <p class="section-description">
                Internal PageRank equity distribution, click-depth distance from homepage, orphan page detection,
                broken hyperlink verification, and descriptive anchor text diversity.
            </p>
    """)

    all_pagerank = {}
    all_click_depth = {}
    for page_url, results in page_results.items():
        link_data = results.get("links", {})
        if link_data.get("pagerank"):
            all_pagerank.update(link_data["pagerank"])
        if link_data.get("click_depth"):
            all_click_depth.update(link_data["click_depth"])

    if all_pagerank and report_mode != "short":
        sorted_pr = sorted(all_pagerank.items(), key=lambda x: x[1], reverse=True)
        parts.append("""
        <h3 class="subsection-title">Internal PageRank Distribution (Top Pages)</h3>
        <table class="data-table">
            <thead>
                <tr>
                    <th>Page URL</th>
                    <th style="width: 140px; text-align: center;">Internal PageRank</th>
                </tr>
            </thead>
            <tbody>
        """)
        for pg_url, pr_score in sorted_pr[:10]:
            display_url = unquote(pg_url)
            if len(display_url) > 80:
                display_url = display_url[:77] + "..."
            parts.append(f"""
                <tr>
                    <td style="font-size: 8.5pt;">{_e(display_url)}</td>
                    <td style="text-align: center; font-weight: 700; color: {score_color(int(pr_score))};">{pr_score:.1f}</td>
                </tr>
            """)
        parts.append("</tbody></table>")

    if all_click_depth and report_mode != "short":
        depth_counts = {}
        unreachable = 0
        for pg_url, depth in all_click_depth.items():
            if depth is None:
                unreachable += 1
            else:
                depth_counts[depth] = depth_counts.get(depth, 0) + 1
        
        parts.append("""
        <h3 class="subsection-title">Click-Depth Distribution</h3>
        <table class="data-table">
            <thead>
                <tr>
                    <th>Click Depth from Homepage</th>
                    <th style="width: 140px; text-align: center;">Number of Pages</th>
                    <th style="width: 140px; text-align: center;">Status</th>
                </tr>
            </thead>
            <tbody>
        """)
        for depth in sorted(depth_counts.keys()):
            count = depth_counts[depth]
            status = "Optimal" if depth <= 3 else "Too Deep"
            status_color = COLOR_GREEN if depth <= 3 else COLOR_RED
            parts.append(f"""
                <tr>
                    <td>{depth} click{'s' if depth != 1 else ''}</td>
                    <td style="text-align: center; font-weight: 700;">{count}</td>
                    <td style="text-align: center; color: {status_color}; font-weight: 600;">{status}</td>
                </tr>
            """)
        if unreachable > 0:
            parts.append(f"""
                <tr>
                    <td style="color: {COLOR_RED};"><strong>Unreachable (no link path)</strong></td>
                    <td style="text-align: center; font-weight: 700; color: {COLOR_RED};">{unreachable}</td>
                    <td style="text-align: center; color: {COLOR_RED}; font-weight: 700;">Critical</td>
                </tr>
            """)
        parts.append("</tbody></table>")

    if report_mode == "short":
        parts.append("""
            <h3 class="subsection-title" style="margin-top: 15px;">Link Structure Defects &amp; Equity Strategy Summary</h3>
        """)
        parts.append(_render_category_summary_table(link_items))
    else:
        parts.append("""
            <h3 class="subsection-title" style="margin-top: 15px;">Link Architecture Defects &amp; Equity Solutions</h3>
        """)
        parts.append(_render_problem_solution_table(link_items, show_page=True))
    parts.append("</div>")

    # 9. IMAGE OPTIMIZATION & MEDIA ASSETS AUDIT
    parts.append(f"""
        <div class="section-container" id="section-9">
            <div class="section-header">
                <h2>9. Image Optimization &amp; Media Assets</h2>
                <div class="section-score-badge" style="color: {score_color(images_score)};">Score: {images_score}/100 (Grade {score_grade(images_score)})</div>
            </div>
            <p class="section-description">
                Inspection of image accessibility (`alt` attribute completeness), explicit `width` and `height`
                dimensions for Cumulative Layout Shift (CLS) prevention, modern image formats (WebP, AVIF), and lazy loading.
            </p>
    """)
    if report_mode == "short":
        parts.append("""
            <h3 class="subsection-title">Media Defects &amp; Optimization Strategy Summary</h3>
        """)
        parts.append(_render_category_summary_table(image_items))
    else:
        parts.append(_render_problem_solution_table(image_items, show_page=True))
    parts.append("</div>")

    # 10. PAGE AUDIT BREAKDOWN
    if report_mode == "short":
        parts.append("""
        <div class="section-container" id="section-10">
            <div class="section-header">
                <h2>10. All Pages Audit Summary Scorecard</h2>
            </div>
            <p class="section-description">
                Consolidated audit score summary across all crawled site URLs.
            </p>
            <table class="data-table">
                <thead>
                    <tr>
                        <th style="width: 250px;">Page URL / Path</th>
                        <th style="text-align: center; width: 65px;">Overall</th>
                        <th style="text-align: center; width: 55px;">Tech</th>
                        <th style="text-align: center; width: 55px;">OnPage</th>
                        <th style="text-align: center; width: 55px;">Content</th>
                        <th style="text-align: center; width: 55px;">Schema</th>
                        <th style="text-align: center; width: 55px;">Perf</th>
                        <th style="text-align: center; width: 55px;">GEO</th>
                        <th style="text-align: center; width: 55px;">Images</th>
                        <th style="text-align: center; width: 55px;">Links</th>
                    </tr>
                </thead>
                <tbody>
        """)
        for page_url, analyzers in page_results.items():
            page_scores = [r.get("score", 0) for r in analyzers.values() if isinstance(r, dict) and "score" in r]
            page_avg = round(sum(page_scores) / len(page_scores)) if page_scores else 0
            parsed = urlparse(page_url)
            display_path = unquote(parsed.path or "/")
            if len(display_path) > 40:
                display_path = display_path[:37] + "..."

            def _get_score_cell(an_key):
                res = analyzers.get(an_key, {})
                s = res.get("score", "N/A") if isinstance(res, dict) else "N/A"
                c = score_color(s) if isinstance(s, int) else COLOR_BLACK
                return f"<td style='text-align: center; font-weight: 700; color: {c}; font-size: 8pt;'>{s}</td>"

            parts.append(f"""
                <tr>
                    <td style="font-size: 8pt; font-family: monospace;"><strong>{_e(display_path)}</strong></td>
                    <td style="text-align: center; font-weight: 800; color: {score_color(page_avg)}; font-size: 8.5pt;">{page_avg}</td>
                    {_get_score_cell("technical")}
                    {_get_score_cell("on_page")}
                    {_get_score_cell("content_quality")}
                    {_get_score_cell("schema")}
                    {_get_score_cell("performance")}
                    {_get_score_cell("ai_search_geo")}
                    {_get_score_cell("images")}
                    {_get_score_cell("links")}
                </tr>
            """)
        parts.append("""
                </tbody>
            </table>
        </div>
        """)
    else:
        # Detailed mode: per-page breakdown (each URL on its own dedicated page)
        for idx, (page_url, analyzers) in enumerate(page_results.items()):
            page_scores = [r.get("score", 0) for r in analyzers.values() if isinstance(r, dict) and "score" in r]
            page_avg = round(sum(page_scores) / len(page_scores)) if page_scores else 0
            parsed = urlparse(page_url)
            display_path = unquote(parsed.path or "/")
            clean_page_url = unquote(page_url)

            page_items = [
                item for item in all_paired_items
                if item.get("page") == page_url
            ]

            if idx == 0:
                header_prefix = """
                <div class="section-header">
                    <h2>10. Page-by-Page Technical &amp; Generative Audit Breakdown</h2>
                </div>
                <p class="section-description">
                    Granular audit records for each crawled URL. Every inspected URL is evaluated with its 
                    individual multi-discipline scorecard and targeted implementation fixes.
                </p>
                """
                container_id = ' id="section-10"'
            else:
                header_prefix = ""
                container_id = ""

            parts.append(f"""
            <div class="section-container"{container_id}>
                {header_prefix}
                <div class="page-audit-header">
                    <div class="page-path">Page: {_e(display_path)}</div>
                    <div class="page-score-badge" style="color: {score_color(page_avg)};">Score: {page_avg}/100 (Grade {score_grade(page_avg)})</div>
                </div>
                <div class="page-url-full">{_e(clean_page_url)}</div>

                <!-- Page Category Scores Sub-table -->
                <table class="data-table" style="margin-bottom: 16px;">
                    <thead>
                        <tr>
            """)

            for an_name in analyzers.keys():
                parts.append(f"<th style='text-align: center; font-size: 7.5pt;'>{_e(an_name.replace('_', ' ').title())}</th>")

            parts.append("""
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
            """)

            for an_res in analyzers.values():
                s = an_res.get("score", "N/A") if isinstance(an_res, dict) else "N/A"
                c = score_color(s) if isinstance(s, int) else COLOR_BLACK
                parts.append(f"<td style='text-align: center; font-weight: 700; color: {c};'>{s}</td>")

            parts.append("""
                        </tr>
                    </tbody>
                </table>
            """)

            # Render the Problem & Solution Table for this page
            parts.append(_render_problem_solution_table(page_items, show_page=False))
            parts.append("</div>")

    roadmap_section_num = 11
    # 11. CRAWL ERRORS (IF ANY)
    if crawl_errors:
        roadmap_section_num = 12
        parts.append("""
        <div class="section-container">
            <div class="section-header">
                <h2 style="color: #b91c1c;">11. Crawl Access Failures</h2>
            </div>
            <table class="data-table">
                <thead>
                    <tr>
                        <th>Target URL</th>
                        <th>Failure Reason</th>
                    </tr>
                </thead>
                <tbody>
        """)
        for err in crawl_errors:
            parts.append(f"""
                    <tr>
                        <td>{_e(err.get("url", ""))}</td>
                        <td style="color: #b91c1c;">{_e(err.get("error", ""))}</td>
                    </tr>
            """)
        parts.append("</tbody></table></div>")

    # 12. PRIORITIZED ENGINEERING ROADMAP & REMEDIATION ASSETS
    parts.append(f"""
        <div class="section-container" id="section-roadmap">
            <div class="section-header">
                <h2>{roadmap_section_num}. Prioritized Engineering Roadmap &amp; Remediation Assets</h2>
            </div>
            <p class="section-description">
                Follow this sequential implementation roadmap to systematically recover link equity, improve indexation, 
                and maximize AI citation visibility.
            </p>

            <div class="action-phase">
                <div class="phase-title" style="color: {COLOR_RED};">Phase 1: Immediate Remediation (Days 1 &ndash; 7)</div>
                <div class="phase-subtitle">Resolve Critical blockers that prevent crawling, indexing, or cause severe ranking loss.</div>
                <ul class="phase-list">
    """)
    for item in all_paired_items:
        f = item["finding"]
        if f.get("severity") == "critical":
            page_clean = unquote(f.get("_page", "Global"))
            parts.append(f"""
                    <li><strong>{_e(f.get("issue"))}</strong> <span style="color: {COLOR_MUTED}; font-size: 8.5pt;">({_e(page_clean)})</span></li>
            """)
    if severity_counts["critical"] == 0:
        parts.append("<li>Zero critical defects found. Proceed directly to Phase 2.</li>")

    parts.append(f"""
                </ul>
            </div>

            <div class="action-phase">
                <div class="phase-title" style="color: {COLOR_RED};">Phase 2: High Priority Structural Enhancements (Weeks 2 &ndash; 3)</div>
                <div class="phase-subtitle">Implement structured data, Core Web Vitals optimizations, and AI citation foundations.</div>
                <ul class="phase-list">
    """)
    for item in all_paired_items:
        f = item["finding"]
        if f.get("severity") == "high":
            page_clean = unquote(f.get("_page", "Global"))
            parts.append(f"""
                    <li><strong>{_e(f.get("issue"))}</strong> <span style="color: {COLOR_MUTED}; font-size: 8.5pt;">({_e(page_clean)})</span></li>
            """)
    if severity_counts["high"] == 0:
        parts.append("<li>Zero high-priority defects found.</li>")

    parts.append(f"""
                </ul>
            </div>

            <div class="action-phase">
                <div class="phase-title" style="color: {COLOR_BLACK};">Phase 3: Continuous GEO &amp; On-Page Refinement (Month 2+)</div>
                <div class="phase-subtitle">Refine content readability, question-based headings, and supplementary schema.</div>
                <ul class="phase-list">
    """)
    for item in all_paired_items:
        f = item["finding"]
        if f.get("severity") == "medium":
            page_clean = unquote(f.get("_page", "Global"))
            parts.append(f"""
                    <li>{_e(f.get("issue"))} <span style="color: {COLOR_MUTED}; font-size: 8.5pt;">({_e(page_clean)})</span></li>
            """)
    if severity_counts["medium"] == 0:
        parts.append("<li>No medium priority improvements needed.</li>")

    parts.append(f"""
                </ul>
            </div>

            <h3 class="subsection-title" style="margin-top: 25px;">Auto-Generated Ready-to-Deploy Assets</h3>
            <p style="font-size: 9pt; margin-bottom: 10px;">
                The following ready-to-deploy files were generated alongside this report and saved to the remediation folder:
            </p>
            <table class="data-table">
                <thead>
                    <tr>
                        <th>File</th>
                        <th>Purpose</th>
                    </tr>
                </thead>
                <tbody>
                    <tr><td><strong>sitemap.xml</strong></td><td>Complete XML sitemap based on all crawled pages with priorities and change frequencies</td></tr>
                    <tr><td><strong>robots.txt</strong></td><td>Optimized robots.txt allowing AI search bots, blocking training bots, declaring sitemap</td></tr>
                    <tr><td><strong>schema/*.json</strong></td><td>Page-type-specific JSON-LD schema (WebSite, Article, Service, Product, etc.) for each crawled page</td></tr>
                    <tr><td><strong>schema/*.html</strong></td><td>Copy-paste HTML script tags with complete JSON-LD for direct embedding</td></tr>
                    <tr><td><strong>llms.txt</strong></td><td>Concise markdown site summary for LLM crawlers (emerging AI search standard)</td></tr>
                    <tr><td><strong>llms-full.txt</strong></td><td>Comprehensive site information document for deep-context AI retrieval</td></tr>
                </tbody>
            </table>
        </div>

        <div class="document-footer">
            <div>Report generated by the Software Department of InersiaLab</div>
            <div>Generated on {timestamp} &bull; Official Technical Audit</div>
        </div>
    </div>
    """)

    return "<!DOCTYPE html><html><head><meta charset='UTF-8'><title>SEO Audit &mdash; " + _e(domain) + "</title></head><body>" + "\n".join(parts) + "</body></html>"


# ---------------------------------------------------------------------------
# Dedicated Problem & Solution Table Component
# ---------------------------------------------------------------------------

def _clean_detail_text(text: str) -> str:
    """Cleans up raw diagnostic text: replaces giant base64 data URIs, unquotes URLs, and formats breaks."""
    if not text:
        return ""

    # Replace huge base64 image strings
    text = re.sub(
        r'data:image/[a-zA-Z0-9\+\.-]+;base64,[a-zA-Z0-9+/=]{20,}',
        '[inline base64 image data]',
        text
    )

    lines = text.split("\n")
    cleaned_lines = []
    for line in lines:
        stripped = line.strip()
        # Clean social intent share URLs with giant parameter query strings
        if "twitter.com/intent/tweet" in stripped or "facebook.com/sharer" in stripped or "linkedin.com/shareArticle" in stripped:
            stripped = re.sub(r'(\?|\&)(url|text|u)=.*', ' [social share widget link]', stripped)

        # Unquote any encoded non-ASCII/Arabic characters
        try:
            stripped = unquote(stripped)
        except Exception:
            pass

        # Truncate extremely long single-token URLs
        if len(stripped) > 90 and " " not in stripped and ("http://" in stripped or "https://" in stripped):
            cleaned_lines.append(stripped[:85] + "...")
        else:
            cleaned_lines.append(stripped)

    escaped = html.escape("\n".join(cleaned_lines))
    return escaped.replace("\n", "<br>")


def _render_problem_solution_table(items: list, show_page: bool = False) -> str:
    """Renders a clean, structured table with direct Problem & Solution pairing for every issue."""
    # Deduplicate items on the SAME page (never show identical issue on the same page twice)
    seen = set()
    deduped_items = []
    for item in items:
        f = item.get("finding", {})
        page = f.get("_page", "")
        issue = f.get("issue", "").strip().lower()
        key = (page, issue)
        if key in seen:
            continue
        seen.add(key)
        deduped_items.append(item)
    items = deduped_items

    if not items:
        return """
        <table class="problem-solution-table">
            <colgroup>
                <col style="width: 45%;">
                <col style="width: 55%;">
            </colgroup>
            <thead>
                <tr>
                    <th class="th-problem">Problem / Defect</th>
                    <th class="th-solution">Solution & Implementation Code</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="2" style="color: #15803d; font-weight: 700; padding: 14px; text-align: center;">
                        [PASSED] All checks compliant with industry standards. Zero defects detected.
                    </td>
                </tr>
            </tbody>
        </table>
        """

    rows = []
    for idx, item in enumerate(items, 1):
        f = item.get("finding", {})
        fix = item.get("fix", {})

        sev = f.get("severity", "info").lower()
        badge_label = SEVERITY_LABELS.get(sev, "[INFORMATIONAL NOTE]")
        badge_color = SEVERITY_TEXT_COLORS.get(sev, COLOR_MUTED)
        cat = f.get("category", "General")
        issue = f.get("issue", "")
        detail = _clean_detail_text(f.get("detail", ""))
        page = f.get("_page", "")

        try:
            clean_page = unquote(page)
        except Exception:
            clean_page = page

        page_html = f'<div class="table-page-ref"><strong>Target URL:</strong> {_e(clean_page)}</div>' if show_page and page else ""

        # Solution content
        sol_content = fix.get("fix", "")
        sol_title = fix.get("issue", "Remediation Steps")
        sol_html = _format_code_blocks(_clean_detail_text(sol_content))

        rows.append(f"""
        <tr>
            <td class="problem-col" style="border-left: 5px solid {badge_color};">
                <div class="problem-header-tag">
                    <span class="problem-badge-large" style="color: {badge_color}; border-color: {badge_color};">{badge_label}</span>
                    <span class="problem-category-tag">{_e(cat)}</span>
                </div>
                {page_html}
                <div class="problem-title-large">{_e(issue)}</div>
                <div class="problem-detail-text">{detail}</div>
            </td>
            <td class="solution-col">
                <div class="solution-header" style="color: {COLOR_GREEN};">
                    <strong>[REMEDIATION FIX]: {_e(sol_title)}</strong>
                </div>
                <div class="solution-body">{sol_html}</div>
            </td>
        </tr>
        """)

    return f"""
    <table class="problem-solution-table">
        <colgroup>
            <col style="width: 45%;">
            <col style="width: 55%;">
        </colgroup>
        <thead>
            <tr>
                <th class="th-problem">Problem / Defect</th>
                <th class="th-solution">Solution & Implementation Code</th>
            </tr>
        </thead>
        <tbody>
            {"".join(rows)}
        </tbody>
    </table>
    """


def _format_code_blocks(text: str) -> str:
    """Format code snippets with clean monospace styling without background fills."""
    lines = text.split("<br>")
    formatted = []
    in_code = False

    for line in lines:
        stripped = line.strip()
        is_code = (
            stripped.startswith("&lt;") or
            stripped.startswith("User-agent:") or
            stripped.startswith("Allow:") or
            stripped.startswith("Disallow:") or
            stripped.startswith("Sitemap:") or
            stripped.startswith("RewriteEngine") or
            stripped.startswith("RewriteCond") or
            stripped.startswith("RewriteRule") or
            stripped.startswith('"@context"') or
            stripped.startswith('"@type"') or
            stripped.startswith("&quot;@context") or
            stripped.startswith("&quot;@type") or
            stripped.startswith("Strict-Transport-Security:") or
            stripped.startswith("X-Content-Type-Options:") or
            stripped.startswith("X-Frame-Options:")
        )

        if is_code and not in_code:
            formatted.append('<div class="code-container">')
            in_code = True
        elif not is_code and in_code:
            formatted.append('</div>')
            in_code = False

        formatted.append(line)

    if in_code:
        formatted.append('</div>')

    return "<br>".join(formatted)


def _e(text) -> str:
    if text is None:
        return ""
    return html.escape(str(text))


# ---------------------------------------------------------------------------
# Category Problems & Fixes Summary Engine (Short Mode)
# ---------------------------------------------------------------------------

def _summarize_category_items(items: list) -> list:
    """Group items by issue concept and produce an executive summary list without raw code dumps."""
    grouped = {}
    sev_rank = {"critical": 4, "high": 3, "medium": 2, "low": 1, "info": 0}

    for item in items:
        f = item.get("finding", {})
        fix = item.get("fix", {})
        issue = f.get("issue", "Unspecified Issue").strip()
        page = item.get("page", "")

        # Clean common prefixes like "[CRITICAL DEFECT]", "[HIGH PRIORITY]", etc.
        clean_issue = re.sub(r"^\[.*?\]\s*", "", issue)
        norm_key = clean_issue.split(" — ")[0].split(" (")[0].strip()

        if norm_key not in grouped:
            fix_summary = ""
            if isinstance(fix, dict):
                fix_summary = fix.get("summary", "")
                if not fix_summary:
                    raw_fix = fix.get("fix", "")
                    if isinstance(raw_fix, str):
                        lines = [l.strip() for l in raw_fix.split("\n") if l.strip() and not l.strip().startswith(("<", "{", "http", "Strict-", "X-", "User-agent", "Sitemap:", "/*", "//"))]
                        fix_summary = " ".join(lines[:2]) if lines else ""
                fix_title = fix.get("title", f"Remediate {norm_key}")
            else:
                fix_title = f"Remediate {norm_key}"

            # Clean any raw html tags
            fix_summary = re.sub(r"<[^>]+>", "", fix_summary).strip()
            # If fix_summary has code artifacts or is too short, provide clean executive instruction
            if '"@context"' in fix_summary or "{" in fix_summary or len(fix_summary) < 20 or fix_summary.startswith("Replace:"):
                norm_lower = norm_key.lower()
                if "h3" in norm_lower or "heading" in norm_lower:
                    fix_summary = "Replace semantic heading tags with standard paragraphs or span elements styled via CSS classes."
                elif "schema" in norm_lower or "structured data" in norm_lower:
                    fix_summary = "Deploy valid Schema.org JSON-LD structured data in document <head> to enable rich search snippets."
                elif "title" in norm_lower:
                    fix_summary = "Ensure title tags are 50-60 characters and contain primary target keywords."
                elif "description" in norm_lower:
                    fix_summary = "Author unique 120-155 character meta descriptions highlighting page value proposition."
                elif "image" in norm_lower or "alt" in norm_lower:
                    fix_summary = "Add descriptive alt attributes and specify width/height dimensions on image elements."
                elif "sitemap" in norm_lower:
                    fix_summary = "Generate and publish an XML sitemap at /sitemap.xml and declare in robots.txt."
                elif "security" in norm_lower or "header" in norm_lower:
                    fix_summary = "Configure modern HTTP security headers (HSTS, CSP, X-Frame-Options) on web server."
                else:
                    fix_summary = f"Implement corrective configuration and structural updates for {norm_key.lower()}."

            if len(fix_summary) > 220:
                fix_summary = fix_summary[:217] + "..."

            detail = f.get("detail", "")
            if not detail:
                detail = clean_issue
            detail = re.sub(r"<[^>]+>", "", detail).strip()
            if "data:image" in detail:
                detail = re.sub(r'data:image/[^;]+;base64,[^\s]+', '[image data]', detail)
            if len(detail) > 220:
                detail = detail[:217] + "..."

            grouped[norm_key] = {
                "issue": norm_key,
                "severity": f.get("severity", "medium").lower(),
                "pages": set(),
                "detail": detail,
                "fix_title": fix_title,
                "fix_summary": fix_summary,
            }

        if page and page != "Site-Wide Infrastructure":
            grouped[norm_key]["pages"].add(page)

        current_sev = grouped[norm_key]["severity"]
        item_sev = f.get("severity", "medium").lower()
        if sev_rank.get(item_sev, 0) > sev_rank.get(current_sev, 0):
            grouped[norm_key]["severity"] = item_sev

    result = []
    for k, v in grouped.items():
        page_count = len(v["pages"])
        if page_count == 0:
            scope_str = "Site-Wide Infrastructure"
        elif page_count == 1:
            p_clean = unquote(urlparse(list(v["pages"])[0]).path or "/")
            scope_str = f"1 Page ({p_clean})"
        else:
            sample = list(v["pages"])[:3]
            sample_paths = [unquote(urlparse(p).path or "/") for p in sample]
            scope_str = f"{page_count} Pages Affected ({', '.join(sample_paths)})"

        result.append({
            "issue": v["issue"],
            "severity": v["severity"],
            "scope": scope_str,
            "problem_summary": v["detail"] or v["issue"],
            "fix_title": v["fix_title"],
            "fix_summary": v["fix_summary"],
        })

    result.sort(key=lambda x: sev_rank.get(x["severity"], 0), reverse=True)
    return result


def _render_category_summary_table(items: list) -> str:
    """Render a clean, concise executive summary table of problems and fixes."""
    summarized = _summarize_category_items(items)
    if not summarized:
        return '<div class="summary-empty-notice">[PASSED] Zero compliance defects identified. All category checks passed.</div>'

    html_out = ['<table class="summary-cat-table">']
    html_out.append('<colgroup><col style="width: 14%;"><col style="width: 43%;"><col style="width: 43%;"></colgroup>')
    html_out.append('<thead><tr>')
    html_out.append('<th style="text-align: center;">Severity</th>')
    html_out.append('<th>Identified Defect &amp; Scope Summary</th>')
    html_out.append('<th>Strategic Fix &amp; Remediation Summary</th>')
    html_out.append('</tr></thead><tbody>')

    for entry in summarized:
        sev = entry["severity"].lower()
        badge_cls = "badge-critical" if sev == "critical" else ("badge-high" if sev == "high" else ("badge-medium" if sev == "medium" else "badge-low"))
        badge_text = sev.upper()

        html_out.append('<tr>')
        html_out.append(f'<td style="text-align: center; vertical-align: top;"><span class="badge {badge_cls}">[{badge_text}]</span></td>')
        html_out.append(f'<td><strong>{_e(entry["issue"])}</strong><br>'
                        f'<span class="summary-scope-tag">{_e(entry["scope"])}</span>'
                        f'<div class="summary-desc-text">{_e(entry["problem_summary"])}</div></td>')
        html_out.append(f'<td><div class="summary-fix-title">{_e(entry["fix_title"])}</div>'
                        f'<div class="summary-fix-text">{_e(entry["fix_summary"])}</div></td>')
        html_out.append('</tr>')

    html_out.append('</tbody></table>')
    return "\n".join(html_out)


# ---------------------------------------------------------------------------
# CSS Design System: 3 Colors, No Shadows, Clean Tables, Pure White
# ---------------------------------------------------------------------------

def _css() -> str:
    return """
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            box-shadow: none !important;
            text-shadow: none !important;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Noto Sans Arabic", "Segoe UI Arabic", Helvetica, Arial, sans-serif;
            font-size: 9.5pt;
            line-height: 1.5;
            color: #111827;
            background: #ffffff;
            -webkit-print-color-adjust: exact;
            print-color-adjust: exact;
        }

        .report-container {
            max-width: 100%;
            margin: 0 auto;
            background: #ffffff;
        }

        .page-break {
            page-break-after: always;
            break-after: page;
            height: 0;
        }

        /* Cover Page */
        .cover-page {
            padding: 60px 40px;
            min-height: 92vh;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            background: #ffffff;
            page-break-after: always;
            break-after: page;
        }

        .header-rule {
            height: 4px;
            background: #111827;
            width: 80px;
            margin-bottom: 24px;
        }

        .organization-tag {
            font-size: 11pt;
            font-weight: 700;
            letter-spacing: 2px;
            color: #111827;
            margin-bottom: 12px;
            text-transform: uppercase;
        }

        .report-main-title {
            font-size: 25pt;
            font-weight: 800;
            line-height: 1.2;
            color: #111827;
            margin-bottom: 12px;
        }

        .report-subtitle {
            font-size: 12pt;
            color: #4b5563;
            font-weight: 500;
            margin-bottom: 40px;
            padding-bottom: 20px;
            border-bottom: 1px solid #e5e7eb;
        }

        .meta-block {
            margin-bottom: 40px;
        }

        .meta-table {
            width: 100%;
            border-collapse: collapse;
            font-size: 9.5pt;
        }

        .meta-table td {
            padding: 8px 0;
            border-bottom: 1px solid #f3f4f6;
        }

        .meta-label {
            width: 160px;
            color: #4b5563;
            font-weight: 600;
        }

        .meta-value {
            color: #111827;
        }

        /* KPI Summary */
        .kpi-summary-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 16px;
            margin-bottom: 40px;
        }

        .kpi-box {
            border: 1px solid #e5e7eb;
            padding: 20px 16px;
            text-align: center;
            background: #ffffff;
        }

        .kpi-number {
            font-size: 24pt;
            font-weight: 800;
            line-height: 1.1;
            margin-bottom: 6px;
        }

        .kpi-title {
            font-size: 8pt;
            font-weight: 600;
            color: #4b5563;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }

        .cover-footer {
            font-size: 8.5pt;
            color: #6b7280;
            border-top: 1px solid #e5e7eb;
            padding-top: 16px;
        }

        /* Standard Sections */
        .section-container {
            padding: 16px 14px 10px 14px;
            page-break-after: always;
            break-after: page;
        }

        .section-container:last-of-type {
            page-break-after: auto;
            break-after: auto;
        }

        .section-header {
            display: flex;
            justify-content: space-between;
            align-items: baseline;
            border-bottom: 2px solid #111827;
            padding-bottom: 8px;
            margin-bottom: 12px;
        }

        .section-header h2 {
            font-size: 13.5pt;
            font-weight: 800;
            color: #111827;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }

        .section-score-badge {
            font-size: 12pt;
            font-weight: 800;
            letter-spacing: 0.5px;
            white-space: nowrap;
        }

        .section-description {
            font-size: 9pt;
            color: #4b5563;
            margin-bottom: 18px;
            line-height: 1.5;
        }

        .subsection-title {
            font-size: 11pt;
            font-weight: 700;
            color: #111827;
            margin-bottom: 10px;
        }

        /* Standard Data Tables */
        .data-table {
            width: 100%;
            border-collapse: collapse;
            font-size: 8.5pt;
            margin-bottom: 20px;
        }

        .data-table th, .data-table td {
            padding: 8px 10px;
            border: 1px solid #e5e7eb;
            text-align: left;
        }

        .data-table th {
            background: #ffffff;
            color: #111827;
            font-weight: 700;
            border-bottom: 2px solid #111827;
            text-transform: uppercase;
            font-size: 7.5pt;
            letter-spacing: 0.5px;
        }

        /* Table of Contents */
        .toc-table td {
            padding: 8px 10px;
            vertical-align: middle;
        }

        .toc-link {
            display: inline-block;
            padding: 2px 7px;
            border: 1px solid #111827;
            color: #111827;
            text-decoration: none;
            font-weight: 700;
            font-size: 7.5pt;
            letter-spacing: 0.5px;
        }

        .toc-link:hover {
            background: #111827;
            color: #ffffff;
        }

        /* Dedicated Problem & Solution Table */
        .problem-solution-table {
            width: 100% !important;
            table-layout: fixed !important;
            border-collapse: collapse !important;
            margin-bottom: 24px;
            font-size: 9pt;
            background: #ffffff;
        }

        .problem-solution-table tr {
            page-break-inside: avoid !important;
            break-inside: avoid !important;
        }

        .problem-solution-table td {
            page-break-inside: avoid !important;
            break-inside: avoid !important;
        }

        .problem-solution-table th.th-problem {
            width: 45% !important;
            background: #ffffff;
            color: #111827;
            font-weight: 800;
            border-top: 2px solid #111827;
            border-bottom: 2px solid #111827;
            padding: 8px 12px;
            text-align: left;
            text-transform: uppercase;
            font-size: 8pt;
            letter-spacing: 0.5px;
        }

        .problem-solution-table th.th-solution {
            width: 55% !important;
            background: #ffffff;
            color: #111827;
            font-weight: 800;
            border-top: 2px solid #111827;
            border-bottom: 2px solid #111827;
            border-left: 1px solid #e5e7eb;
            padding: 8px 12px;
            text-align: left;
            text-transform: uppercase;
            font-size: 8pt;
            letter-spacing: 0.5px;
        }

        .problem-col {
            width: 45% !important;
            max-width: 45% !important;
            padding: 12px 14px !important;
            background: #ffffff;
            border-bottom: 1px solid #e5e7eb;
            vertical-align: top;
            overflow-wrap: break-word !important;
            word-wrap: break-word !important;
            word-break: normal !important;
        }

        .problem-header-tag {
            display: flex;
            align-items: center;
            gap: 8px;
            margin-bottom: 6px;
            flex-wrap: wrap;
        }

        .problem-badge-large {
            font-size: 7.5pt !important;
            font-weight: 800 !important;
            padding: 2px 6px !important;
            border: 1px solid !important;
            border-radius: 3px !important;
            text-transform: uppercase !important;
            letter-spacing: 0.5px !important;
            display: inline-block !important;
            line-height: 1.2 !important;
        }

        .problem-category-tag {
            font-size: 8pt !important;
            font-weight: 700 !important;
            color: #4b5563 !important;
            text-transform: uppercase !important;
            letter-spacing: 0.5px !important;
        }

        .problem-title-large {
            font-size: 9.5pt !important;
            font-weight: 700 !important;
            color: #111827 !important;
            margin-top: 4px !important;
            margin-bottom: 6px !important;
            line-height: 1.3 !important;
        }

        .table-page-ref {
            font-size: 8pt !important;
            color: #4b5563 !important;
            margin-bottom: 6px !important;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Noto Sans Arabic", monospace;
            overflow-wrap: break-word !important;
            word-break: break-all !important;
            line-height: 1.35 !important;
        }

        .problem-detail-text {
            font-size: 8.5pt;
            color: #374151;
            line-height: 1.45;
            overflow-wrap: break-word;
            word-break: break-word;
        }

        .solution-col {
            width: 55% !important;
            max-width: 55% !important;
            padding: 12px 14px !important;
            background: #ffffff;
            border-bottom: 1px solid #e5e7eb;
            border-left: 1px solid #e5e7eb;
            vertical-align: top;
            overflow-wrap: break-word !important;
            word-wrap: break-word !important;
            word-break: normal !important;
        }

        .solution-header {
            font-size: 8.5pt !important;
            font-weight: 700 !important;
            margin-bottom: 6px !important;
            line-height: 1.3 !important;
        }

        .solution-body {
            font-size: 8.5pt;
            color: #111827;
            line-height: 1.45;
            overflow-wrap: break-word;
            word-break: break-word;
        }

        .code-container {
            font-family: "Courier New", Courier, monospace;
            font-size: 8pt;
            border: 1px solid #e5e7eb;
            padding: 6px 8px;
            margin: 6px 0;
            background: #ffffff;
            color: #111827;
            white-space: pre-wrap;
            word-break: break-all;
        }

        /* Category Summary Table (Short Mode) */
        .summary-cat-table {
            width: 100% !important;
            border-collapse: collapse !important;
            margin-top: 10px !important;
            margin-bottom: 20px !important;
            border: 1px solid #e5e7eb !important;
            table-layout: fixed !important;
        }

        .summary-cat-table th {
            background-color: #f9fafb !important;
            color: #111827 !important;
            font-size: 7.5pt !important;
            font-weight: 700 !important;
            text-transform: uppercase !important;
            letter-spacing: 0.5px !important;
            padding: 8px 10px !important;
            border-bottom: 2px solid #111827 !important;
            border-right: 1px solid #e5e7eb !important;
            text-align: left;
        }

        .summary-cat-table td {
            padding: 9px 10px !important;
            border-bottom: 1px solid #e5e7eb !important;
            border-right: 1px solid #e5e7eb !important;
            font-size: 8.5pt !important;
            vertical-align: top !important;
            line-height: 1.4 !important;
            overflow-wrap: break-word !important;
            word-break: break-word !important;
        }

        .summary-scope-tag {
            font-size: 7.5pt !important;
            font-weight: 700 !important;
            color: #4b5563 !important;
            display: inline-block !important;
            margin-top: 2px !important;
            margin-bottom: 4px !important;
            text-transform: uppercase !important;
        }

        .summary-desc-text {
            color: #374151 !important;
            font-size: 8.5pt !important;
            line-height: 1.4 !important;
        }

        .summary-fix-title {
            font-weight: 700 !important;
            color: #15803d !important;
            font-size: 8.5pt !important;
            margin-bottom: 3px !important;
        }

        .summary-fix-text {
            color: #111827 !important;
            font-size: 8.5pt !important;
            line-height: 1.4 !important;
        }

        .summary-empty-notice {
            padding: 12px 14px !important;
            border: 1px solid #e5e7eb !important;
            background: #ffffff !important;
            color: #15803d !important;
            font-size: 8.5pt !important;
            font-weight: 700 !important;
            margin-top: 8px !important;
            margin-bottom: 16px !important;
        }

        .badge {
            font-size: 7.5pt !important;
            font-weight: 800 !important;
            padding: 1.5px 5px !important;
            border: 1px solid !important;
            border-radius: 2px !important;
            text-transform: uppercase !important;
            letter-spacing: 0.5px !important;
            display: inline-block !important;
            line-height: 1.2 !important;
        }

        .badge-critical, .badge-high {
            border-color: #b91c1c !important;
            color: #b91c1c !important;
        }

        .badge-medium {
            border-color: #111827 !important;
            color: #111827 !important;
        }

        .badge-low, .badge-info {
            border-color: #4b5563 !important;
            color: #4b5563 !important;
        }

        /* Page Audit Section */
        .page-audit-wrapper {
            border: 1px solid #111827;
            padding: 16px;
            margin-bottom: 24px;
            background: #ffffff;
        }

        .page-audit-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 1px solid #111827;
            padding-bottom: 8px;
            margin-bottom: 6px;
        }

        .page-path {
            font-size: 11pt;
            font-weight: 800;
            color: #111827;
        }

        .page-score-badge {
            font-size: 11pt;
            font-weight: 800;
        }

        .page-url-full {
            font-size: 8pt;
            color: #6b7280;
            margin-bottom: 14px;
            word-break: break-all;
            font-family: monospace;
        }

        /* Action Phases */
        .action-phase {
            border: 1px solid #e5e7eb;
            padding: 14px;
            margin-bottom: 14px;
        }

        .phase-title {
            font-size: 10.5pt;
            font-weight: 800;
            margin-bottom: 4px;
        }

        .phase-subtitle {
            font-size: 8.5pt;
            color: #4b5563;
            margin-bottom: 8px;
        }

        .phase-list {
            padding-left: 18px;
            font-size: 8.5pt;
            color: #111827;
        }

        .phase-list li {
            margin-bottom: 4px;
        }

        /* Document Footer */
        .document-footer {
            border-top: 1px solid #111827;
            padding-top: 10px;
            margin-top: 25px;
            display: flex;
            justify-content: space-between;
            font-size: 8pt;
            color: #6b7280;
        }
    </style>
    """


# ---------------------------------------------------------------------------
# PDF Renderer via Playwright
# ---------------------------------------------------------------------------

def render_pdf(html_content: str, output_path: str):
    """Render HTML string to A4 PDF using headless Chromium."""
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        print("ERROR: Playwright not installed. Install with: pip install playwright")
        sys.exit(1)

    playwright_paths = [
        os.path.expanduser("~/.gemini/config/skills/claude-seo/ms-playwright"),
        os.path.expanduser("~/.claude/skills/seo/ms-playwright"),
    ]

    browser_path = None
    for pw_path in playwright_paths:
        if os.path.exists(pw_path):
            for dirpath, dirnames, filenames in os.walk(pw_path):
                for fn in filenames:
                    if fn in ("chrome.exe", "chromium.exe", "chromium"):
                        browser_path = os.path.join(dirpath, fn)
                        break
                if browser_path:
                    break
        if browser_path:
            break

    if os.path.exists(playwright_paths[0]):
        os.environ["PLAYWRIGHT_BROWSERS_PATH"] = playwright_paths[0]

    print(f"  [reporter] Rendering PDF with Playwright...")

    with sync_playwright() as p:
        launch_args = {"headless": True}
        if browser_path:
            launch_args["executable_path"] = browser_path

        browser = p.chromium.launch(**launch_args)
        page = browser.new_page()
        page.set_content(html_content, wait_until="networkidle")

        page.pdf(
            path=output_path,
            format="A4",
            margin={"top": "12mm", "bottom": "12mm", "left": "8mm", "right": "8mm"},
            print_background=True,
        )
        browser.close()

    print(f"  [reporter] PDF saved successfully: {output_path}")
