"""agy-seo: Executive HTML Report Builder & Playwright PDF Renderer.

Presents all SEO audit findings directly in a clean, professional Table Format:
- Column 1: Problem / Defect (Category, Severity, Issue name, Location, Diagnostic Detail)
- Column 2: Solution / Fix (Actionable implementation instructions and copy-paste code)
- Strict 3-color palette: Black (text/borders), Red (problems), Green (solutions).
- No icons/emojis, no box shadows, pure white background.
- Official attribution: 'Report generated by the Software Department of InersiaLab'.
"""

import html
import json
import os
import re
import sys
from datetime import datetime
from urllib.parse import urlparse, unquote

if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass


# ---------------------------------------------------------------------------
# Strict 3-Color Scheme & Professional Severity Labels
# ---------------------------------------------------------------------------

COLOR_BLACK = "#111827"
COLOR_RED = "#b91c1c"
COLOR_GREEN = "#15803d"
COLOR_MUTED = "#4b5563"
COLOR_BORDER = "#e5e7eb"

SEVERITY_TEXT_COLORS = {
    "critical": COLOR_RED,
    "high": COLOR_RED,
    "medium": COLOR_RED,
    "low": COLOR_BLACK,
    "info": COLOR_MUTED,
}

SEVERITY_LABELS = {
    "critical": "[CRITICAL DEFECT]",
    "high": "[HIGH PRIORITY]",
    "medium": "[MEDIUM PRIORITY]",
    "low": "[LOW PRIORITY]",
    "info": "[INFORMATIONAL NOTE]",
}


def score_color(score: int) -> str:
    """Returns Red for poor/failing scores, Green for strong/good scores, Black for neutral."""
    if score >= 85:
        return COLOR_GREEN
    elif score >= 70:
        return COLOR_BLACK
    return COLOR_RED


def score_grade(score: int) -> str:
    if score >= 90: return "A"
    if score >= 80: return "B"
    if score >= 70: return "C"
    if score >= 60: return "D"
    return "F"


# ---------------------------------------------------------------------------
# Intelligent Finding & Fix Pairing Engine
# ---------------------------------------------------------------------------

def _pair_finding_with_solution(finding: dict, available_fixes: list) -> dict:
    """Matches a finding with its corresponding fix or generates an accurate fallback solution."""
    issue_lower = finding.get("issue", "").lower()
    cat_lower = finding.get("category", "").lower()

    # 1. Exact match first
    for fix in available_fixes:
        fix_issue_lower = fix.get("issue", "").lower()
        if fix_issue_lower == issue_lower:
            return fix

    # 2. Specific keyword direct matching
    SPECIFIC_KEYWORDS = [
        "orphan", "anchor", "broken", "nofollow", "redirect", "sitemap",
        "robots.txt", "schema", "json-ld", "h1", "title", "meta description",
        "ttfb", "cls", "lcp", "render-blocking", "dimensions", "lazy",
        "crawler", "searchgpt", "perplexity", "llms.txt", "freshness", "thin",
        "security", "https", "canonical"
    ]
    for kw in SPECIFIC_KEYWORDS:
        if kw in issue_lower or kw in cat_lower:
            for fix in available_fixes:
                if kw in fix.get("issue", "").lower():
                    return fix

    # 3. Substring match
    for fix in available_fixes:
        fix_issue_lower = fix.get("issue", "").lower()
        if fix_issue_lower in issue_lower or issue_lower in fix_issue_lower:
            return fix

    # 4. Significant non-generic word overlap (exclude common stop words)
    STOP_WORDS = {"links", "link", "page", "pages", "site", "found", "using", "with", "from", "causes", "other", "than"}
    issue_words = [w for w in re.findall(r'\b\w{4,}\b', issue_lower) if w not in STOP_WORDS]
    best_fix = None
    max_overlap = 0
    for fix in available_fixes:
        fix_words = set(re.findall(r'\b\w{4,}\b', fix.get("issue", "").lower()))
        overlap = len(fix_words.intersection(issue_words))
        if overlap > max_overlap:
            max_overlap = overlap
            best_fix = fix

    if best_fix and max_overlap > 0:
        return best_fix

    # 5. Comprehensive fallback solution generation if no explicit fix was returned
    return {
        "issue": finding.get("issue", "Remediation Action"),
        "fix": _generate_fallback_solution(finding),
    }


def _generate_fallback_solution(finding: dict) -> str:
    """Generates concrete, copy-paste remediation steps based on the finding category and issue."""
    issue = finding.get("issue", "").lower()
    cat = finding.get("category", "").lower()
    detail = finding.get("detail", "")

    if "orphan" in issue or "orphan" in cat:
        return (
            "Add internal contextual links to this orphan page from relevant category and parent pages:\n"
            "1. Identify 2-3 topically related parent or pillar pages\n"
            "2. Add contextual in-body links using descriptive anchor text\n"
            "3. Ensure the page is included in the XML sitemap"
        )
    elif "broken" in issue or "broken" in cat:
        return (
            "Inspect and repair or remove broken outbound hyperlinks:\n"
            "1. Replace dead social sharing links with active standard widget links\n"
            "2. Update outdated external references to live destinations\n"
            "3. Remove links to non-existent resources"
        )
    elif "title" in issue or "title" in cat:
        return (
            "Craft a unique, compelling <title> tag between 50-60 characters containing the primary keyword and brand name:\n\n"
            "<title>Primary Keyword &mdash; Secondary Service | Brand Name</title>\n\n"
            "Ensure the title accurately reflects the main page topic and avoids keyword stuffing."
        )
    elif "meta description" in issue or "meta description" in cat:
        return (
            "Add a concise meta description between 120-155 characters that summarizes the page and includes a call-to-action:\n\n"
            '<meta name="description" content="Discover professional solutions and services tailored to your needs. Contact our team today for a consultation." />'
        )
    elif "h1" in issue or "heading" in cat:
        return (
            "Structure headings hierarchically. Ensure exactly one semantic <h1> element is present at the top of the body:\n\n"
            "<h1>Descriptive Primary Topic Heading</h1>\n\n"
            "Convert any duplicate or secondary <h1> elements into <h2> or <h3> subheadings."
        )
    elif "sitemap" in issue or "sitemap" in cat:
        return (
            "Generate and publish an XML sitemap declaring all canonical indexable pages:\n"
            "1. Place the generated file at domain root: /sitemap.xml\n"
            "2. Reference the sitemap inside robots.txt:\n"
            "   Sitemap: https://yourdomain.com/sitemap.xml\n"
            "3. Submit the sitemap in Google Search Console under 'Sitemaps'."
        )
    elif "robots.txt" in issue or "crawlability" in cat:
        return (
            "Create or correct the robots.txt file at domain root:\n\n"
            "User-agent: *\n"
            "Allow: /\n\n"
            "Sitemap: https://yourdomain.com/sitemap.xml"
        )
    elif "alt" in issue:
        return (
            "Provide concise, descriptive alt attributes for all <img> tags to ensure search indexing and accessibility:\n\n"
            '<img src="example.jpg" alt="Clear description of the visual content and context" />\n\n'
            'For purely decorative images, set an empty alt attribute: alt=""'
        )
    elif "width" in issue or "height" in issue or "cls" in issue:
        return (
            "Specify explicit width and height dimensions on all image tags to prevent Cumulative Layout Shift (CLS):\n\n"
            '<img src="example.jpg" width="800" height="600" alt="Description" />\n\n'
            "Alternatively, reserve space in CSS: img { aspect-ratio: 16/9; width: 100%; height: auto; }"
        )
    elif "schema" in issue or "structured data" in cat:
        return (
            "Implement Schema.org JSON-LD structured data in the document <head>:\n\n"
            '<script type="application/ld+json">\n'
            "{\n"
            '  "@context": "https://schema.org",\n'
            '  "@type": "WebPage",\n'
            '  "name": "Page Title",\n'
            '  "url": "https://yourdomain.com/page"\n'
            "}\n"
            "</script>"
        )
    elif "security" in issue or "https" in issue:
        return (
            "Configure modern security headers in your web server (Apache/Nginx/Cloudflare):\n\n"
            "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload\n"
            "X-Content-Type-Options: nosniff\n"
            "X-Frame-Options: SAMEORIGIN\n"
            "Referrer-Policy: strict-origin-when-cross-origin"
        )
    elif "render-blocking" in issue or "render blocking" in issue:
        return (
            "Defer non-critical external JavaScript files so HTML parsing can complete without interruption:\n\n"
            '<script src="bundle.js" defer></script>\n\n'
            "For non-critical stylesheets, load asynchronously using rel='preload' or media='print'."
        )
    elif "ttfb" in issue:
        return (
            "Reduce server response latency (TTFB):\n"
            "1. Implement server-side caching (Redis, Varnish, or CMS cache)\n"
            "2. Route traffic through a global CDN (e.g. Cloudflare)\n"
            "3. Optimize database queries and slow PHP/Node.js backend execution"
        )
    elif "ai" in issue or "bot" in issue or "geo" in cat:
        return (
            "Optimize for Generative Search Engines (SearchGPT, Perplexity, Claude):\n"
            "1. Allow AI search bots in robots.txt:\n"
            "   User-agent: OAI-SearchBot\n   Allow: /\n   User-agent: PerplexityBot\n   Allow: /\n"
            "2. Publish /llms.txt at domain root containing a clean markdown summary of core services."
        )
    elif "thin" in issue or "word count" in issue:
        return (
            "Expand textual content to at least 350-500 words of comprehensive, original material "
            "addressing the user's primary search intent and topic questions."
        )
    elif "internal link" in issue:
        return (
            "Add contextual internal links within body copy connecting this page to related service "
            "and category pages to distribute link equity and assist crawlers."
        )
    else:
        return (
            "Review the diagnostic detail and implement corrective code adhering to Google Search Essentials "
            "and W3C web standards."
        )


def _filter_items_by_category(items: list, category_key: str) -> list:
    """Filter paired problem-solution items strictly by audit discipline."""
    cat_key = category_key.lower().strip()
    matched = []

    for item in items:
        an = item.get("analyzer", "").lower()
        f = item.get("finding", {})
        issue = f.get("issue", "").lower()
        cat = f.get("category", "").lower()

        if cat_key == "technical":
            if an in ("technical", "robots & sitemaps") or "technical" in an or "robots" in an or "sitemap" in an or cat in ("technical", "security", "infrastructure"):
                matched.append(item)
            elif an == "cross-page patterns" and not any(w in issue for w in ("title", "description", "orphan")):
                matched.append(item)
        elif cat_key == "onpage":
            if an in ("on_page", "onpage") or "on_page" in an or cat in ("on-page", "onpage", "meta", "headings"):
                matched.append(item)
            elif an == "cross-page patterns" and any(w in issue for w in ("title", "description")):
                matched.append(item)
        elif cat_key == "geo":
            if an in ("ai_search_geo", "geo") or "geo" in an or "ai" in an or cat in ("geo", "ai search", "generative seo"):
                matched.append(item)
        elif cat_key == "content":
            if an in ("content_quality", "content") or "content" in an or cat in ("content", "e-e-a-t", "eeat"):
                matched.append(item)
        elif cat_key == "schema":
            if an in ("schema", "schema_analyzer") or "schema" in an or cat in ("schema", "structured data"):
                matched.append(item)
        elif cat_key == "performance":
            if an in ("performance",) or "performance" in an or cat in ("performance", "speed"):
                matched.append(item)
        elif cat_key == "links":
            if an in ("links",) or "link" in an or cat in ("links", "internal links"):
                matched.append(item)
            elif an == "cross-page patterns" and "orphan" in issue:
                matched.append(item)
        elif cat_key == "images":
            if an in ("images",) or "image" in an or cat in ("images", "media"):
                matched.append(item)

    return matched


# ---------------------------------------------------------------------------
# HTML Report Builder
# ---------------------------------------------------------------------------

def build_report_html(audit_result: dict) -> str:
    """Build an executive HTML report with all results presented in Problem & Solution Tables."""
    domain = audit_result["domain"]
    base_url = audit_result["base_url"]
    pages_crawled = audit_result["pages_crawled"]
    site_scores = audit_result["site_scores"]
    overall_score = audit_result["overall_score"]
    page_results = audit_result["page_results"]
    site_findings = audit_result.get("site_findings", {})
    crawl_errors = audit_result.get("crawl_errors", [])
    timestamp = datetime.now().strftime("%B %d, %Y at %H:%M")

    # Collect and classify all findings paired with solutions
    all_paired_items = []

    # Page-level findings
    for page_url, page in page_results.items():
        for analyzer_name, result in page.items():
            if isinstance(result, dict) and "findings" in result:
                avail_fixes = result.get("fixes", [])
                for f in result["findings"]:
                    f["_page"] = page_url
                    f["_analyzer"] = analyzer_name
                    sol = _pair_finding_with_solution(f, avail_fixes)
                    all_paired_items.append({
                        "finding": f,
                        "fix": sol,
                        "page": page_url,
                        "analyzer": analyzer_name,
                    })

    # Site-level findings
    for analyzer_name, result in site_findings.items():
        if isinstance(result, dict) and "findings" in result:
            avail_fixes = result.get("fixes", [])
            for f in result["findings"]:
                f["_page"] = "Site-Wide Infrastructure"
                f["_analyzer"] = analyzer_name
                sol = _pair_finding_with_solution(f, avail_fixes)
                all_paired_items.append({
                    "finding": f,
                    "fix": sol,
                    "page": "Site-Wide Infrastructure",
                    "analyzer": analyzer_name,
                })

    # Count issues by severity
    severity_counts = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
    for item in all_paired_items:
        sev = item["finding"].get("severity", "info").lower()
        severity_counts[sev] = severity_counts.get(sev, 0) + 1

    total_issues = sum(v for k, v in severity_counts.items() if k != "info")

    parts = []
    parts.append(_css())
    parts.append(f"""
    <div class="report-container">
        <!-- COVER PAGE -->
        <div class="cover-page">
            <div class="header-rule"></div>
            <div class="organization-tag">INERSIALAB SOFTWARE DEPARTMENT</div>
            <h1 class="report-main-title">Comprehensive Technical & Generative SEO Audit</h1>
            <div class="report-subtitle">Report generated by the Software Department of InersiaLab</div>

            <div class="meta-block">
                <table class="meta-table">
                    <tr>
                        <td class="meta-label">Target Domain:</td>
                        <td class="meta-value"><strong>{_e(domain)}</strong></td>
                    </tr>
                    <tr>
                        <td class="meta-label">Target URL:</td>
                        <td class="meta-value">{_e(base_url)}</td>
                    </tr>
                    <tr>
                        <td class="meta-label">Audit Date:</td>
                        <td class="meta-value">{timestamp}</td>
                    </tr>
                    <tr>
                        <td class="meta-label">Pages Inspected:</td>
                        <td class="meta-value">{pages_crawled}</td>
                    </tr>
                </table>
            </div>

            <div class="kpi-summary-grid">
                <div class="kpi-box">
                    <div class="kpi-number" style="color: {score_color(overall_score)};">{overall_score}/100</div>
                    <div class="kpi-title">Overall Score (Grade {score_grade(overall_score)})</div>
                </div>
                <div class="kpi-box">
                    <div class="kpi-number" style="color: {COLOR_RED if severity_counts['critical'] > 0 else COLOR_BLACK};">{severity_counts['critical']}</div>
                    <div class="kpi-title">Critical Defects</div>
                </div>
                <div class="kpi-box">
                    <div class="kpi-number" style="color: {COLOR_RED if severity_counts['high'] > 0 else COLOR_BLACK};">{severity_counts['high']}</div>
                    <div class="kpi-title">High Priority Defects</div>
                </div>
                <div class="kpi-box">
                    <div class="kpi-number" style="color: {COLOR_BLACK};">{total_issues}</div>
                    <div class="kpi-title">Total Issues Identified</div>
                </div>
            </div>

            <div class="cover-footer">
                Report generated by the Software Department of InersiaLab &bull; All Rights Reserved
            </div>
        </div>

        <!-- 1. EXECUTIVE SUMMARY -->
        <div class="section-container">
            <div class="section-header">
                <h2>1. Executive Summary & Category Breakdown</h2>
            </div>
            <p class="section-description">
                Evaluation across the core SEO disciplines. Scores reflect strict compliance with modern search engine 
                guidelines, crawl efficiency, structured data standards, and generative AI citability.
            </p>

            <table class="data-table">
                <thead>
                    <tr>
                        <th>Audit Category</th>
                        <th style="width: 120px; text-align: center;">Score</th>
                        <th style="width: 130px; text-align: center;">Status</th>
                        <th>Evaluation Summary</th>
                    </tr>
                </thead>
                <tbody>
    """)

    for cat_name, cat_score in site_scores.items():
        status_text = "Satisfactory" if cat_score >= 85 else ("Needs Improvement" if cat_score >= 70 else "Action Required")
        status_color = score_color(cat_score)
        summary_text = (
            "Well optimized with no major impediments detected." if cat_score >= 85
            else ("Minor issues found that require attention." if cat_score >= 70
            else "Significant compliance failures identified that directly harm performance.")
        )
        parts.append(f"""
                    <tr>
                        <td><strong>{_e(cat_name)}</strong></td>
                        <td style="text-align: center; font-weight: 700; color: {status_color};">{cat_score}/100</td>
                        <td style="text-align: center; font-weight: 600; color: {status_color};">{status_text}</td>
                        <td>{summary_text}</td>
                    </tr>
        """)

    parts.append(f"""
                </tbody>
            </table>

            <div style="margin-top: 25px;">
                <h3 class="subsection-title">Issues Summary by Severity</h3>
                <table class="data-table" style="width: 100%;">
                    <thead>
                        <tr>
                            <th style="color: {COLOR_RED};">Critical Priority</th>
                            <th style="color: {COLOR_RED};">High Priority</th>
                            <th>Medium Priority</th>
                            <th>Low Priority</th>
                            <th>Informational Notes</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr style="text-align: center; font-size: 14px; font-weight: 700;">
                            <td style="color: {COLOR_RED};">{severity_counts['critical']}</td>
                            <td style="color: {COLOR_RED};">{severity_counts['high']}</td>
                            <td>{severity_counts['medium']}</td>
                            <td>{severity_counts['low']}</td>
                            <td>{severity_counts['info']}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    """)

    # Score retrieval helper
    def _cat_score(*keys) -> int:
        for k in keys:
            if k in site_scores:
                return site_scores[k]
            for sk, sv in site_scores.items():
                if sk.lower() == k.lower():
                    return sv
        return 0

    tech_score = _cat_score("Technical", "Robots & Sitemaps")
    onpage_score = _cat_score("On Page")
    geo_score = _cat_score("Ai Search Geo", "Geo")
    content_score = _cat_score("Content Quality", "Content")
    schema_score = _cat_score("Schema")
    perf_score = _cat_score("Performance")
    links_score = _cat_score("Links")
    images_score = _cat_score("Images")

    tech_items = _filter_items_by_category(all_paired_items, "technical")
    onpage_items = _filter_items_by_category(all_paired_items, "onpage")
    geo_items = _filter_items_by_category(all_paired_items, "geo")
    content_items = _filter_items_by_category(all_paired_items, "content")
    schema_items = _filter_items_by_category(all_paired_items, "schema")
    perf_items = _filter_items_by_category(all_paired_items, "performance")
    link_items = _filter_items_by_category(all_paired_items, "links")
    image_items = _filter_items_by_category(all_paired_items, "images")

    # 2. TECHNICAL & INFRASTRUCTURE SEO AUDIT
    parts.append(f"""
        <div class="section-container">
            <div class="section-header">
                <h2>2. Technical &amp; Infrastructure SEO</h2>
                <div class="section-score-badge" style="color: {score_color(tech_score)};">Score: {tech_score}/100 (Grade {score_grade(tech_score)})</div>
            </div>
            <p class="section-description">
                Evaluation of domain-level server configurations, HTTPS security headers, HTTP status codes,
                canonical URL integrity, robots.txt crawl directives, XML sitemap validation, response compression,
                and modern HTTP/2 / HTTP/3 protocol support.
            </p>
    """)
    parts.append(_render_problem_solution_table(tech_items, show_page=True))
    parts.append("</div>")

    # 3. ON-PAGE SEO & METADATA ARCHITECTURE AUDIT
    parts.append(f"""
        <div class="section-container">
            <div class="section-header">
                <h2>3. On-Page SEO &amp; Metadata Architecture</h2>
                <div class="section-score-badge" style="color: {score_color(onpage_score)};">Score: {onpage_score}/100 (Grade {score_grade(onpage_score)})</div>
            </div>
            <p class="section-description">
                Inspection of HTML title tag relevance and length, meta description search-snippet appeal,
                H1&ndash;H6 heading hierarchy, Open Graph social cards, and Twitter Card metadata across all crawled URLs.
            </p>
    """)
    parts.append(_render_problem_solution_table(onpage_items, show_page=True))
    parts.append("</div>")

    # 4. GENERATIVE ENGINE OPTIMIZATION (GEO & AI SEARCH) AUDIT
    parts.append(f"""
        <div class="section-container">
            <div class="section-header">
                <h2>4. Generative Engine Optimization (GEO &amp; AI Search)</h2>
                <div class="section-score-badge" style="color: {score_color(geo_score)};">Score: {geo_score}/100 (Grade {score_grade(geo_score)})</div>
            </div>
            <p class="section-description">
                Readiness evaluation for generative AI answer engines including OpenAI SearchGPT, Perplexity AI,
                Anthropic Claude, and Google AI Overviews. Evaluates platform bot access, LLM quotability,
                conversational clarity, and search intent alignment.
            </p>
    """)

    # First page GEO data (homepage or primary landing page)
    first_geo = None
    for page_url, results in page_results.items():
        geo_data = results.get("ai_search_geo", {})
        if geo_data:
            first_geo = geo_data
            break

    if first_geo:
        # Platform readiness table
        platform_scores = first_geo.get("platform_scores", {})
        if platform_scores:
            parts.append("""
            <h3 class="subsection-title">AI Platform Readiness Scores</h3>
            <table class="data-table">
                <thead>
                    <tr>
                        <th>AI Search Platform</th>
                        <th style="width: 140px; text-align: center;">Readiness Score</th>
                        <th style="width: 140px; text-align: center;">Status</th>
                    </tr>
                </thead>
                <tbody>
            """)
            for platform, pscore in platform_scores.items():
                status = "Ready" if pscore >= 70 else ("Partial" if pscore >= 40 else "Blocked")
                parts.append(f"""
                    <tr>
                        <td><strong>{_e(platform)}</strong></td>
                        <td style="text-align: center; font-weight: 700; color: {score_color(pscore)};">{pscore}/100</td>
                        <td style="text-align: center; font-weight: 600; color: {score_color(pscore)};">{status}</td>
                    </tr>
                """)
            parts.append("</tbody></table>")

        # Quotability analysis
        quotability = first_geo.get("quotability", {})
        if quotability and quotability.get("total_count", 0) > 0:
            parts.append(f"""
            <h3 class="subsection-title">LLM Quotability &amp; Citation Analysis</h3>
            <table class="data-table">
                <thead>
                    <tr>
                        <th>Metric</th>
                        <th style="width: 200px; text-align: center;">Value</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><strong>Overall Quotability Score</strong></td>
                        <td style="text-align: center; font-weight: 700; color: {score_color(quotability['overall_score'])};">{quotability['overall_score']}/100</td>
                    </tr>
                    <tr>
                        <td>Total Passages Analyzed</td>
                        <td style="text-align: center;">{quotability['total_count']}</td>
                    </tr>
                    <tr>
                        <td>Citable Passages (Score 60+)</td>
                        <td style="text-align: center; font-weight: 700; color: {COLOR_GREEN if quotability['citable_count'] > 0 else COLOR_RED};">{quotability['citable_count']}</td>
                    </tr>
                </tbody>
            </table>
            """)

        # Intent matrix
        intent_data = first_geo.get("intent_analysis", {})
        if intent_data and intent_data.get("intents"):
            parts.append(f"""
            <h3 class="subsection-title">AEO 5-Intent Matrix</h3>
            <p style="font-size: 8.5pt; color: {COLOR_MUTED}; margin-bottom: 8px;">
                Primary detected intent: <strong>{_e(intent_data.get('primary_intent', 'unknown').title())}</strong>
            </p>
            <table class="data-table">
                <thead>
                    <tr>
                        <th>Search Intent</th>
                        <th style="width: 140px; text-align: center;">Optimization Score</th>
                        <th>Key Signals Detected</th>
                    </tr>
                </thead>
                <tbody>
            """)
            for intent_name, intent_info in intent_data.get("intents", {}).items():
                signals = ", ".join(intent_info.get("signals", [])[:3]) or "None detected"
                iscore = intent_info.get("score", 0)
                parts.append(f"""
                    <tr>
                        <td><strong>{_e(intent_name.title())}</strong></td>
                        <td style="text-align: center; font-weight: 700; color: {score_color(iscore)};">{iscore}/100</td>
                        <td style="font-size: 8.5pt;">{_e(signals)}</td>
                    </tr>
                """)
            parts.append("</tbody></table>")

    parts.append("""
            <h3 class="subsection-title" style="margin-top: 15px;">GEO Defects &amp; AI Search Optimization Solutions</h3>
    """)
    parts.append(_render_problem_solution_table(geo_items, show_page=True))
    parts.append("</div>")

    # 5. CONTENT QUALITY & E-E-A-T VALIDATION AUDIT
    parts.append(f"""
        <div class="section-container">
            <div class="section-header">
                <h2>5. Content Quality &amp; E-E-A-T Validation</h2>
                <div class="section-score-badge" style="color: {score_color(content_score)};">Score: {content_score}/100 (Grade {score_grade(content_score)})</div>
            </div>
            <p class="section-description">
                Evaluation of substantive body copy depth, Flesch reading complexity, author attribution signals,
                citation and factual density, and thin content detection aligned with Google's Experience, Expertise,
                Authoritativeness, and Trustworthiness guidelines.
            </p>
    """)
    parts.append(_render_problem_solution_table(content_items, show_page=True))
    parts.append("</div>")

    # 6. SCHEMA & STRUCTURED DATA (JSON-LD) AUDIT
    parts.append(f"""
        <div class="section-container">
            <div class="section-header">
                <h2>6. Schema &amp; Structured Data (JSON-LD)</h2>
                <div class="section-score-badge" style="color: {score_color(schema_score)};">Score: {schema_score}/100 (Grade {score_grade(schema_score)})</div>
            </div>
            <p class="section-description">
                Validation of Schema.org syntax integrity, JSON-LD script formatting, Google Rich Snippet
                eligibility (Organization, WebSite, BreadcrumbList, Article, Product, Service), and entity graph relations.
            </p>
    """)
    parts.append(_render_problem_solution_table(schema_items, show_page=True))
    parts.append("</div>")

    # 7. PERFORMANCE & CORE WEB VITALS AUDIT
    parts.append(f"""
        <div class="section-container">
            <div class="section-header">
                <h2>7. Performance &amp; Core Web Vitals</h2>
                <div class="section-score-badge" style="color: {score_color(perf_score)};">Score: {perf_score}/100 (Grade {score_grade(perf_score)})</div>
            </div>
            <p class="section-description">
                Analysis of initial server response latency (Time to First Byte &ndash; TTFB), DOM tree complexity,
                render-blocking JavaScript and CSS resources, and overall page weight impacting user engagement and conversion.
            </p>
    """)
    parts.append(_render_problem_solution_table(perf_items, show_page=True))
    parts.append("</div>")

    # 8. LINK ARCHITECTURE & INTERNAL EQUITY AUDIT
    parts.append(f"""
        <div class="section-container">
            <div class="section-header">
                <h2>8. Link Architecture &amp; Internal Equity</h2>
                <div class="section-score-badge" style="color: {score_color(links_score)};">Score: {links_score}/100 (Grade {score_grade(links_score)})</div>
            </div>
            <p class="section-description">
                Internal PageRank equity distribution, click-depth distance from homepage, orphan page detection,
                broken hyperlink verification, and descriptive anchor text diversity.
            </p>
    """)

    all_pagerank = {}
    all_click_depth = {}
    for page_url, results in page_results.items():
        link_data = results.get("links", {})
        if link_data.get("pagerank"):
            all_pagerank.update(link_data["pagerank"])
        if link_data.get("click_depth"):
            all_click_depth.update(link_data["click_depth"])

    if all_pagerank:
        sorted_pr = sorted(all_pagerank.items(), key=lambda x: x[1], reverse=True)
        parts.append("""
        <h3 class="subsection-title">Internal PageRank Distribution (Top Pages)</h3>
        <table class="data-table">
            <thead>
                <tr>
                    <th>Page URL</th>
                    <th style="width: 140px; text-align: center;">Internal PageRank</th>
                </tr>
            </thead>
            <tbody>
        """)
        for pg_url, pr_score in sorted_pr[:10]:
            display_url = unquote(pg_url)
            if len(display_url) > 80:
                display_url = display_url[:77] + "..."
            parts.append(f"""
                <tr>
                    <td style="font-size: 8.5pt;">{_e(display_url)}</td>
                    <td style="text-align: center; font-weight: 700; color: {score_color(int(pr_score))};">{pr_score:.1f}</td>
                </tr>
            """)
        parts.append("</tbody></table>")

    if all_click_depth:
        depth_counts = {}
        unreachable = 0
        for url, depth in all_click_depth.items():
            if depth == -1:
                unreachable += 1
            else:
                depth_counts[depth] = depth_counts.get(depth, 0) + 1
        
        parts.append("""
        <h3 class="subsection-title">Click-Depth Distribution</h3>
        <table class="data-table">
            <thead>
                <tr>
                    <th>Click Depth from Homepage</th>
                    <th style="width: 140px; text-align: center;">Number of Pages</th>
                    <th style="width: 140px; text-align: center;">Status</th>
                </tr>
            </thead>
            <tbody>
        """)
        for depth in sorted(depth_counts.keys()):
            count = depth_counts[depth]
            status = "Optimal" if depth <= 3 else "Too Deep"
            status_color = COLOR_GREEN if depth <= 3 else COLOR_RED
            parts.append(f"""
                <tr>
                    <td>{depth} click{'s' if depth != 1 else ''}</td>
                    <td style="text-align: center; font-weight: 700;">{count}</td>
                    <td style="text-align: center; color: {status_color}; font-weight: 600;">{status}</td>
                </tr>
            """)
        if unreachable > 0:
            parts.append(f"""
                <tr>
                    <td style="color: {COLOR_RED};"><strong>Unreachable (no link path)</strong></td>
                    <td style="text-align: center; font-weight: 700; color: {COLOR_RED};">{unreachable}</td>
                    <td style="text-align: center; color: {COLOR_RED}; font-weight: 700;">Critical</td>
                </tr>
            """)
        parts.append("</tbody></table>")

    parts.append("""
            <h3 class="subsection-title" style="margin-top: 15px;">Link Architecture Defects &amp; Equity Solutions</h3>
    """)
    parts.append(_render_problem_solution_table(link_items, show_page=True))
    parts.append("</div>")

    # 9. IMAGE OPTIMIZATION & MEDIA ASSETS AUDIT
    parts.append(f"""
        <div class="section-container">
            <div class="section-header">
                <h2>9. Image Optimization &amp; Media Assets</h2>
                <div class="section-score-badge" style="color: {score_color(images_score)};">Score: {images_score}/100 (Grade {score_grade(images_score)})</div>
            </div>
            <p class="section-description">
                Inspection of image accessibility (`alt` attribute completeness), explicit `width` and `height`
                dimensions for Cumulative Layout Shift (CLS) prevention, modern image formats (WebP, AVIF), and lazy loading.
            </p>
    """)
    parts.append(_render_problem_solution_table(image_items, show_page=True))
    parts.append("</div>")

    # 10. PAGE-BY-PAGE AUDIT BREAKDOWN (EACH URL ON ITS OWN DEDICATED PAGE)
    for idx, (page_url, analyzers) in enumerate(page_results.items()):
        page_scores = [r.get("score", 0) for r in analyzers.values() if isinstance(r, dict) and "score" in r]
        page_avg = round(sum(page_scores) / len(page_scores)) if page_scores else 0
        parsed = urlparse(page_url)
        display_path = unquote(parsed.path or "/")
        clean_page_url = unquote(page_url)

        page_items = [
            item for item in all_paired_items
            if item.get("page") == page_url
        ]

        if idx == 0:
            header_prefix = """
            <div class="section-header">
                <h2>10. Page-by-Page Technical &amp; Generative Audit Breakdown</h2>
            </div>
            <p class="section-description">
                Granular audit records for each crawled URL. Every inspected URL is evaluated with its 
                individual multi-discipline scorecard and targeted implementation fixes.
            </p>
            """
        else:
            header_prefix = ""

        parts.append(f"""
        <div class="section-container">
            {header_prefix}
            <div class="page-audit-header">
                <div class="page-path">Page: {_e(display_path)}</div>
                <div class="page-score-badge" style="color: {score_color(page_avg)};">Score: {page_avg}/100 (Grade {score_grade(page_avg)})</div>
            </div>
            <div class="page-url-full">{_e(clean_page_url)}</div>

            <!-- Page Category Scores Sub-table -->
            <table class="data-table" style="margin-bottom: 16px;">
                <thead>
                    <tr>
        """)

        for an_name in analyzers.keys():
            parts.append(f"<th style='text-align: center; font-size: 7.5pt;'>{_e(an_name.replace('_', ' ').title())}</th>")

        parts.append("""
                    </tr>
                </thead>
                <tbody>
                    <tr>
        """)

        for an_res in analyzers.values():
            s = an_res.get("score", "N/A") if isinstance(an_res, dict) else "N/A"
            c = score_color(s) if isinstance(s, int) else COLOR_BLACK
            parts.append(f"<td style='text-align: center; font-weight: 700; color: {c};'>{s}</td>")

        parts.append("""
                    </tr>
                </tbody>
            </table>
        """)

        # Render the Problem & Solution Table for this page
        parts.append(_render_problem_solution_table(page_items, show_page=False))
        parts.append("</div>")

    roadmap_section_num = 11
    # 11. CRAWL ERRORS (IF ANY)
    if crawl_errors:
        roadmap_section_num = 12
        parts.append("""
        <div class="section-container">
            <div class="section-header">
                <h2 style="color: #b91c1c;">11. Crawl Access Failures</h2>
            </div>
            <table class="data-table">
                <thead>
                    <tr>
                        <th>Target URL</th>
                        <th>Failure Reason</th>
                    </tr>
                </thead>
                <tbody>
        """)
        for err in crawl_errors:
            parts.append(f"""
                    <tr>
                        <td>{_e(err.get("url", ""))}</td>
                        <td style="color: #b91c1c;">{_e(err.get("error", ""))}</td>
                    </tr>
            """)
        parts.append("</tbody></table></div>")

    # 12. PRIORITIZED ENGINEERING ROADMAP & REMEDIATION ASSETS
    parts.append(f"""
        <div class="section-container">
            <div class="section-header">
                <h2>{roadmap_section_num}. Prioritized Engineering Roadmap &amp; Remediation Assets</h2>
            </div>
            <p class="section-description">
                Follow this sequential implementation roadmap to systematically recover link equity, improve indexation, 
                and maximize AI citation visibility.
            </p>

            <div class="action-phase">
                <div class="phase-title" style="color: {COLOR_RED};">Phase 1: Immediate Remediation (Days 1 &ndash; 7)</div>
                <div class="phase-subtitle">Resolve Critical blockers that prevent crawling, indexing, or cause severe ranking loss.</div>
                <ul class="phase-list">
    """)
    for item in all_paired_items:
        f = item["finding"]
        if f.get("severity") == "critical":
            page_clean = unquote(f.get("_page", "Global"))
            parts.append(f"""
                    <li><strong>{_e(f.get("issue"))}</strong> <span style="color: {COLOR_MUTED}; font-size: 8.5pt;">({_e(page_clean)})</span></li>
            """)
    if severity_counts["critical"] == 0:
        parts.append("<li>Zero critical defects found. Proceed directly to Phase 2.</li>")

    parts.append(f"""
                </ul>
            </div>

            <div class="action-phase">
                <div class="phase-title" style="color: {COLOR_RED};">Phase 2: High Priority Structural Enhancements (Weeks 2 &ndash; 3)</div>
                <div class="phase-subtitle">Implement structured data, Core Web Vitals optimizations, and AI citation foundations.</div>
                <ul class="phase-list">
    """)
    for item in all_paired_items:
        f = item["finding"]
        if f.get("severity") == "high":
            page_clean = unquote(f.get("_page", "Global"))
            parts.append(f"""
                    <li><strong>{_e(f.get("issue"))}</strong> <span style="color: {COLOR_MUTED}; font-size: 8.5pt;">({_e(page_clean)})</span></li>
            """)
    if severity_counts["high"] == 0:
        parts.append("<li>Zero high-priority defects found.</li>")

    parts.append(f"""
                </ul>
            </div>

            <div class="action-phase">
                <div class="phase-title" style="color: {COLOR_BLACK};">Phase 3: Continuous GEO &amp; On-Page Refinement (Month 2+)</div>
                <div class="phase-subtitle">Refine content readability, question-based headings, and supplementary schema.</div>
                <ul class="phase-list">
    """)
    for item in all_paired_items:
        f = item["finding"]
        if f.get("severity") == "medium":
            page_clean = unquote(f.get("_page", "Global"))
            parts.append(f"""
                    <li>{_e(f.get("issue"))} <span style="color: {COLOR_MUTED}; font-size: 8.5pt;">({_e(page_clean)})</span></li>
            """)
    if severity_counts["medium"] == 0:
        parts.append("<li>No medium priority improvements needed.</li>")

    parts.append(f"""
                </ul>
            </div>

            <h3 class="subsection-title" style="margin-top: 25px;">Auto-Generated Ready-to-Deploy Assets</h3>
            <p style="font-size: 9pt; margin-bottom: 10px;">
                The following ready-to-deploy files were generated alongside this report and saved to the remediation folder:
            </p>
            <table class="data-table">
                <thead>
                    <tr>
                        <th>File</th>
                        <th>Purpose</th>
                    </tr>
                </thead>
                <tbody>
                    <tr><td><strong>sitemap.xml</strong></td><td>Complete XML sitemap based on all crawled pages with priorities and change frequencies</td></tr>
                    <tr><td><strong>robots.txt</strong></td><td>Optimized robots.txt allowing AI search bots, blocking training bots, declaring sitemap</td></tr>
                    <tr><td><strong>schema/*.json</strong></td><td>Page-type-specific JSON-LD schema (WebSite, Article, Service, Product, etc.) for each crawled page</td></tr>
                    <tr><td><strong>schema/*.html</strong></td><td>Copy-paste HTML script tags with complete JSON-LD for direct embedding</td></tr>
                    <tr><td><strong>llms.txt</strong></td><td>Concise markdown site summary for LLM crawlers (emerging AI search standard)</td></tr>
                    <tr><td><strong>llms-full.txt</strong></td><td>Comprehensive site information document for deep-context AI retrieval</td></tr>
                </tbody>
            </table>
        </div>

        <div class="document-footer">
            <div>Report generated by the Software Department of InersiaLab</div>
            <div>Generated on {timestamp} &bull; Official Technical Audit</div>
        </div>
    </div>
    """)

    return "<!DOCTYPE html><html><head><meta charset='UTF-8'><title>SEO Audit &mdash; " + _e(domain) + "</title></head><body>" + "\n".join(parts) + "</body></html>"


# ---------------------------------------------------------------------------
# Dedicated Problem & Solution Table Component
# ---------------------------------------------------------------------------

def _clean_detail_text(text: str) -> str:
    """Cleans up raw diagnostic text: replaces giant base64 data URIs, unquotes URLs, and formats breaks."""
    if not text:
        return ""

    # Replace huge base64 image strings
    text = re.sub(
        r'data:image/[a-zA-Z0-9\+\.-]+;base64,[a-zA-Z0-9+/=]{20,}',
        '[inline base64 image data]',
        text
    )

    lines = text.split("\n")
    cleaned_lines = []
    for line in lines:
        stripped = line.strip()
        # Clean social intent share URLs with giant parameter query strings
        if "twitter.com/intent/tweet" in stripped or "facebook.com/sharer" in stripped or "linkedin.com/shareArticle" in stripped:
            stripped = re.sub(r'(\?|\&)(url|text|u)=.*', ' [social share widget link]', stripped)

        # Unquote any encoded non-ASCII/Arabic characters
        try:
            stripped = unquote(stripped)
        except Exception:
            pass

        # Truncate extremely long single-token URLs
        if len(stripped) > 90 and " " not in stripped and ("http://" in stripped or "https://" in stripped):
            cleaned_lines.append(stripped[:85] + "...")
        else:
            cleaned_lines.append(stripped)

    escaped = html.escape("\n".join(cleaned_lines))
    return escaped.replace("\n", "<br>")


def _render_problem_solution_table(items: list, show_page: bool = False) -> str:
    """Renders a clean, structured table with direct Problem & Solution pairing for every issue."""
    if not items:
        return """
        <table class="problem-solution-table">
            <colgroup>
                <col style="width: 50%;">
                <col style="width: 50%;">
            </colgroup>
            <thead>
                <tr>
                    <th class="th-problem">Problem / Defect</th>
                    <th class="th-solution">Solution & Implementation Code</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="2" style="color: #15803d; font-weight: 700; padding: 14px; text-align: center;">
                        [PASSED] All checks compliant with industry standards. Zero defects detected.
                    </td>
                </tr>
            </tbody>
        </table>
        """

    rows = []
    for idx, item in enumerate(items, 1):
        f = item.get("finding", {})
        fix = item.get("fix", {})

        sev = f.get("severity", "info").lower()
        badge_label = SEVERITY_LABELS.get(sev, "[INFORMATIONAL NOTE]")
        badge_color = SEVERITY_TEXT_COLORS.get(sev, COLOR_MUTED)
        cat = f.get("category", "General")
        issue = f.get("issue", "")
        detail = _clean_detail_text(f.get("detail", ""))
        page = f.get("_page", "")

        try:
            clean_page = unquote(page)
        except Exception:
            clean_page = page

        page_html = f'<div class="table-page-ref"><strong>Target URL:</strong> {_e(clean_page)}</div>' if show_page and page else ""

        # Solution content
        sol_content = fix.get("fix", "")
        sol_title = fix.get("issue", "Remediation Steps")
        sol_html = _format_code_blocks(_clean_detail_text(sol_content))

        rows.append(f"""
        <tr>
            <td class="problem-col" style="border-left: 5px solid {badge_color};">
                <div class="problem-header-tag">
                    <span class="problem-badge-large" style="color: {badge_color}; border-color: {badge_color};">{badge_label}</span>
                    <span class="problem-category-tag">{_e(cat)}</span>
                </div>
                {page_html}
                <div class="problem-title-large">{_e(issue)}</div>
                <div class="problem-detail-text">{detail}</div>
            </td>
            <td class="solution-col">
                <div class="solution-header" style="color: {COLOR_GREEN};">
                    <strong>[REMEDIATION FIX]: {_e(sol_title)}</strong>
                </div>
                <div class="solution-body">{sol_html}</div>
            </td>
        </tr>
        """)

    return f"""
    <table class="problem-solution-table">
        <colgroup>
            <col style="width: 50%;">
            <col style="width: 50%;">
        </colgroup>
        <thead>
            <tr>
                <th class="th-problem">Problem / Defect</th>
                <th class="th-solution">Solution & Implementation Code</th>
            </tr>
        </thead>
        <tbody>
            {"".join(rows)}
        </tbody>
    </table>
    """


def _format_code_blocks(text: str) -> str:
    """Format code snippets with clean monospace styling without background fills."""
    lines = text.split("<br>")
    formatted = []
    in_code = False

    for line in lines:
        stripped = line.strip()
        is_code = (
            stripped.startswith("&lt;") or
            stripped.startswith("User-agent:") or
            stripped.startswith("Allow:") or
            stripped.startswith("Disallow:") or
            stripped.startswith("Sitemap:") or
            stripped.startswith("RewriteEngine") or
            stripped.startswith("RewriteCond") or
            stripped.startswith("RewriteRule") or
            stripped.startswith('"@context"') or
            stripped.startswith('"@type"') or
            stripped.startswith("&quot;@context") or
            stripped.startswith("&quot;@type") or
            stripped.startswith("Strict-Transport-Security:") or
            stripped.startswith("X-Content-Type-Options:") or
            stripped.startswith("X-Frame-Options:")
        )

        if is_code and not in_code:
            formatted.append('<div class="code-container">')
            in_code = True
        elif not is_code and in_code:
            formatted.append('</div>')
            in_code = False

        formatted.append(line)

    if in_code:
        formatted.append('</div>')

    return "<br>".join(formatted)


def _e(text) -> str:
    if text is None:
        return ""
    return html.escape(str(text))


# ---------------------------------------------------------------------------
# CSS Design System: 3 Colors, No Shadows, Clean Tables, Pure White
# ---------------------------------------------------------------------------

def _css() -> str:
    return """
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            box-shadow: none !important;
            text-shadow: none !important;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Noto Sans Arabic", "Segoe UI Arabic", Helvetica, Arial, sans-serif;
            font-size: 9.5pt;
            line-height: 1.5;
            color: #111827;
            background: #ffffff;
            -webkit-print-color-adjust: exact;
            print-color-adjust: exact;
        }

        .report-container {
            max-width: 100%;
            margin: 0 auto;
            background: #ffffff;
        }

        .page-break {
            page-break-after: always;
            break-after: page;
            height: 0;
        }

        /* Cover Page */
        .cover-page {
            padding: 60px 40px;
            min-height: 92vh;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            background: #ffffff;
            page-break-after: always;
            break-after: page;
        }

        .header-rule {
            height: 4px;
            background: #111827;
            width: 80px;
            margin-bottom: 24px;
        }

        .organization-tag {
            font-size: 11pt;
            font-weight: 700;
            letter-spacing: 2px;
            color: #111827;
            margin-bottom: 12px;
            text-transform: uppercase;
        }

        .report-main-title {
            font-size: 25pt;
            font-weight: 800;
            line-height: 1.2;
            color: #111827;
            margin-bottom: 12px;
        }

        .report-subtitle {
            font-size: 12pt;
            color: #4b5563;
            font-weight: 500;
            margin-bottom: 40px;
            padding-bottom: 20px;
            border-bottom: 1px solid #e5e7eb;
        }

        .meta-block {
            margin-bottom: 40px;
        }

        .meta-table {
            width: 100%;
            border-collapse: collapse;
            font-size: 9.5pt;
        }

        .meta-table td {
            padding: 8px 0;
            border-bottom: 1px solid #f3f4f6;
        }

        .meta-label {
            width: 160px;
            color: #4b5563;
            font-weight: 600;
        }

        .meta-value {
            color: #111827;
        }

        /* KPI Summary */
        .kpi-summary-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 16px;
            margin-bottom: 40px;
        }

        .kpi-box {
            border: 1px solid #e5e7eb;
            padding: 20px 16px;
            text-align: center;
            background: #ffffff;
        }

        .kpi-number {
            font-size: 24pt;
            font-weight: 800;
            line-height: 1.1;
            margin-bottom: 6px;
        }

        .kpi-title {
            font-size: 8pt;
            font-weight: 600;
            color: #4b5563;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }

        .cover-footer {
            font-size: 8.5pt;
            color: #6b7280;
            border-top: 1px solid #e5e7eb;
            padding-top: 16px;
        }

        /* Standard Sections */
        .section-container {
            padding: 24px 36px 14px 36px;
            page-break-after: always;
            break-after: page;
        }

        .section-container:last-of-type {
            page-break-after: auto;
            break-after: auto;
        }

        .section-header {
            display: flex;
            justify-content: space-between;
            align-items: baseline;
            border-bottom: 2px solid #111827;
            padding-bottom: 8px;
            margin-bottom: 12px;
        }

        .section-header h2 {
            font-size: 13.5pt;
            font-weight: 800;
            color: #111827;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }

        .section-score-badge {
            font-size: 12pt;
            font-weight: 800;
            letter-spacing: 0.5px;
            white-space: nowrap;
        }

        .section-description {
            font-size: 9pt;
            color: #4b5563;
            margin-bottom: 18px;
            line-height: 1.5;
        }

        .subsection-title {
            font-size: 11pt;
            font-weight: 700;
            color: #111827;
            margin-bottom: 10px;
        }

        /* Standard Data Tables */
        .data-table {
            width: 100%;
            border-collapse: collapse;
            font-size: 8.5pt;
            margin-bottom: 20px;
        }

        .data-table th, .data-table td {
            padding: 8px 10px;
            border: 1px solid #e5e7eb;
            text-align: left;
        }

        .data-table th {
            background: #ffffff;
            color: #111827;
            font-weight: 700;
            border-bottom: 2px solid #111827;
            text-transform: uppercase;
            font-size: 7.5pt;
            letter-spacing: 0.5px;
        }

        /* Dedicated Problem & Solution Table */
        .problem-solution-table {
            width: 100% !important;
            table-layout: fixed !important;
            border-collapse: collapse !important;
            margin-bottom: 24px;
            font-size: 9pt;
            background: #ffffff;
        }

        .problem-solution-table tr {
            page-break-inside: avoid !important;
            break-inside: avoid !important;
        }

        .problem-solution-table td {
            page-break-inside: avoid !important;
            break-inside: avoid !important;
        }

        .problem-solution-table th.th-problem {
            width: 50% !important;
            background: #ffffff;
            color: #111827;
            font-weight: 800;
            border-top: 2px solid #111827;
            border-bottom: 2px solid #111827;
            padding: 10px 16px;
            text-align: left;
            text-transform: uppercase;
            font-size: 8.5pt;
            letter-spacing: 0.5px;
        }

        .problem-solution-table th.th-solution {
            width: 50% !important;
            background: #ffffff;
            color: #111827;
            font-weight: 800;
            border-top: 2px solid #111827;
            border-bottom: 2px solid #111827;
            border-left: 1px solid #e5e7eb;
            padding: 10px 16px;
            text-align: left;
            text-transform: uppercase;
            font-size: 8.5pt;
            letter-spacing: 0.5px;
        }

        .problem-col {
            width: 50% !important;
            max-width: 50% !important;
            padding: 16px 18px !important;
            background: #ffffff;
            border-bottom: 1px solid #e5e7eb;
            vertical-align: top;
            overflow-wrap: break-word !important;
            word-wrap: break-word !important;
            word-break: normal !important;
        }

        .problem-header-tag {
            display: flex;
            align-items: center;
            gap: 12px;
            margin-bottom: 10px;
            flex-wrap: wrap;
        }

        .problem-badge-large {
            font-size: 10.5pt !important;
            font-weight: 800 !important;
            padding: 4px 10px !important;
            border: 2px solid !important;
            border-radius: 4px !important;
            text-transform: uppercase !important;
            letter-spacing: 0.8px !important;
            display: inline-block !important;
            line-height: 1.15 !important;
        }

        .problem-category-tag {
            font-size: 10pt !important;
            font-weight: 700 !important;
            color: #374151 !important;
            text-transform: uppercase !important;
            letter-spacing: 0.6px !important;
        }

        .problem-title-large {
            font-size: 11.5pt !important;
            font-weight: 800 !important;
            color: #111827 !important;
            margin-top: 6px !important;
            margin-bottom: 8px !important;
            line-height: 1.35 !important;
        }

        .table-page-ref {
            font-size: 8.5pt !important;
            color: #4b5563 !important;
            margin-bottom: 8px !important;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Noto Sans Arabic", monospace;
            overflow-wrap: break-word !important;
            word-break: break-all !important;
            line-height: 1.4 !important;
        }

        .problem-detail-text {
            font-size: 9pt;
            color: #374151;
            line-height: 1.5;
            overflow-wrap: break-word;
            word-break: break-word;
        }

        .solution-col {
            width: 50% !important;
            max-width: 50% !important;
            padding: 16px 18px !important;
            background: #ffffff;
            border-bottom: 1px solid #e5e7eb;
            border-left: 1px solid #e5e7eb;
            vertical-align: top;
            overflow-wrap: break-word !important;
            word-wrap: break-word !important;
            word-break: normal !important;
        }

        .solution-header {
            font-size: 10pt !important;
            font-weight: 800 !important;
            margin-bottom: 8px !important;
            line-height: 1.35 !important;
        }

        .solution-body {
            font-size: 9pt;
            color: #111827;
            line-height: 1.5;
            overflow-wrap: break-word;
            word-break: break-word;
        }

        .code-container {
            font-family: "Courier New", Courier, monospace;
            font-size: 8pt;
            border: 1px solid #e5e7eb;
            padding: 6px 8px;
            margin: 6px 0;
            background: #ffffff;
            color: #111827;
            white-space: pre-wrap;
            word-break: break-all;
        }

        /* Page Audit Section */
        .page-audit-wrapper {
            border: 1px solid #111827;
            padding: 16px;
            margin-bottom: 24px;
            background: #ffffff;
        }

        .page-audit-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 1px solid #111827;
            padding-bottom: 8px;
            margin-bottom: 6px;
        }

        .page-path {
            font-size: 11pt;
            font-weight: 800;
            color: #111827;
        }

        .page-score-badge {
            font-size: 11pt;
            font-weight: 800;
        }

        .page-url-full {
            font-size: 8pt;
            color: #6b7280;
            margin-bottom: 14px;
            word-break: break-all;
            font-family: monospace;
        }

        /* Action Phases */
        .action-phase {
            border: 1px solid #e5e7eb;
            padding: 14px;
            margin-bottom: 14px;
        }

        .phase-title {
            font-size: 10.5pt;
            font-weight: 800;
            margin-bottom: 4px;
        }

        .phase-subtitle {
            font-size: 8.5pt;
            color: #4b5563;
            margin-bottom: 8px;
        }

        .phase-list {
            padding-left: 18px;
            font-size: 8.5pt;
            color: #111827;
        }

        .phase-list li {
            margin-bottom: 4px;
        }

        /* Document Footer */
        .document-footer {
            border-top: 1px solid #111827;
            padding-top: 10px;
            margin-top: 25px;
            display: flex;
            justify-content: space-between;
            font-size: 8pt;
            color: #6b7280;
        }
    </style>
    """


# ---------------------------------------------------------------------------
# PDF Renderer via Playwright
# ---------------------------------------------------------------------------

def render_pdf(html_content: str, output_path: str):
    """Render HTML string to A4 PDF using headless Chromium."""
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        print("ERROR: Playwright not installed. Install with: pip install playwright")
        sys.exit(1)

    playwright_paths = [
        os.path.expanduser("~/.gemini/config/skills/claude-seo/ms-playwright"),
        os.path.expanduser("~/.claude/skills/seo/ms-playwright"),
    ]

    browser_path = None
    for pw_path in playwright_paths:
        if os.path.exists(pw_path):
            for dirpath, dirnames, filenames in os.walk(pw_path):
                for fn in filenames:
                    if fn in ("chrome.exe", "chromium.exe", "chromium"):
                        browser_path = os.path.join(dirpath, fn)
                        break
                if browser_path:
                    break
        if browser_path:
            break

    if os.path.exists(playwright_paths[0]):
        os.environ["PLAYWRIGHT_BROWSERS_PATH"] = playwright_paths[0]

    print(f"  [reporter] Rendering PDF with Playwright...")

    with sync_playwright() as p:
        launch_args = {"headless": True}
        if browser_path:
            launch_args["executable_path"] = browser_path

        browser = p.chromium.launch(**launch_args)
        page = browser.new_page()
        page.set_content(html_content, wait_until="networkidle")

        page.pdf(
            path=output_path,
            format="A4",
            margin={"top": "15mm", "bottom": "15mm", "left": "14mm", "right": "14mm"},
            print_background=True,
        )
        browser.close()

    print(f"  [reporter] PDF saved successfully: {output_path}")
