"""InersiaLab Software Department — Cybersecurity & Server Hardening Engine.

Comprehensive security auditor and server hardening generator:
1. Technical & Security Header Inspection (HSTS, CSP, X-Frame-Options, info leaks)
2. CORS Misconfiguration Probe (Reflected origin with credentials)
3. WordPress User Enumeration (/wp-json/wp/v2/users, ?author=1)
4. XML-RPC Endpoint & Amplification (/xmlrpc.php system.multicall)
5. Sensitive Files & Endpoints (/readme.html, /license.txt, .env, .git, debug logs)
6. Form PII & Submission Security (GET method, validation, honeypot)
7. Transport & SSL/TLS Verification (TLS 1.3/1.2, cipher, legacy protocol rejection)
8. DNS Anti-Spoofing & Domain Hardening (SPF, DMARC p=none vs p=reject, CAA, DNSSEC)
9. Headless Browser Inspection (Console errors, 404s, reverse tabnabbing)
10. Executive PDF Report Generation (ReportLab) to user's Downloads folder
11. Turnkey Code Patches (.htaccess, functions.php, form JS/HTML, Master AI Fix Prompt)
"""

import os
import sys
import re
import ssl
import json
import socket
import time
from datetime import datetime
from urllib.parse import urlparse, quote

DOWNLOADS_DIR = os.path.join(os.path.expanduser("~"), "Downloads")

# ---------------------------------------------------------------------------
# ReportLab Import with graceful fallback
# ---------------------------------------------------------------------------
try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, HRFlowable
    )
    from reportlab.pdfgen import canvas
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False


class NumberedCanvas(canvas.Canvas if REPORTLAB_AVAILABLE else object):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica-Bold", 7.5)
        self.setFillColor(colors.HexColor("#4b5563"))
        
        if self._pageNumber > 1:
            self.drawString(36, 812, "INERSIALAB CYBERSECURITY & SERVER HARDENING AUDIT")
            self.setFont("Helvetica", 7.5)
            self.drawString(275, 812, "|   Confidential Technical Assessment")
            self.drawRightString(559, 812, datetime.now().strftime("%B %d, %Y"))
            self.setStrokeColor(colors.HexColor("#e5e7eb"))
            self.setLineWidth(0.6)
            self.line(36, 806, 559, 806)

        self.setStrokeColor(colors.HexColor("#e5e7eb"))
        self.setLineWidth(0.6)
        self.line(36, 38, 559, 38)
        
        self.setFont("Helvetica", 7.5)
        self.setFillColor(colors.HexColor("#6b7280"))
        self.drawString(36, 26, "CONFIDENTIAL  |  Generated by InersiaLab Software Department Audit Suite")
        self.drawRightString(559, 26, f"Page {self._pageNumber} of {page_count}")
        self.restoreState()


class SecurityAuditRunner:
    def __init__(self, target_url: str, log_callback=None):
        raw_url = target_url.strip()
        if not raw_url.startswith("http://") and not raw_url.startswith("https://"):
            raw_url = "https://" + raw_url
        self.target_url = raw_url
        self.parsed = urlparse(self.target_url)
        self.domain = self.parsed.netloc.split(":")[0]
        self.scheme = self.parsed.scheme
        self.log_callback = log_callback or (lambda msg: None)
        self.findings = []
        self.logs = []

    def log(self, message: str):
        self.logs.append(message)
        self.log_callback(message)

    def add_finding(self, finding_id: str, severity: str, title: str, location: str,
                    impact: str, recommendation: str, status: str = "failed", details: str = ""):
        self.findings.append({
            "id": finding_id,
            "severity": severity.lower(),  # critical, high, medium, low, passed
            "title": title,
            "location": location,
            "impact": impact,
            "recommendation": recommendation,
            "status": status,
            "details": details
        })

    def run(self) -> dict:
        self.log(f"\n============================================================")
        self.log(f"  InersiaLab Software Department — Cybersecurity Audit")
        self.log(f"  Target: {self.target_url}")
        self.log(f"  Domain: {self.domain}")
        self.log(f"  Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        self.log(f"============================================================\n")

        # Step 1: DNS & IP Resolution
        self.log("[+] Step 1/9: DNS & Host Network Probing...")
        ip_address = self._resolve_ip()
        
        # Step 2: SSL/TLS Transport
        self.log("[+] Step 2/9: SSL/TLS Transport Encryption & Cipher Testing...")
        tls_info = self._audit_tls()

        # Step 3: HTTP Headers & Information Leaks
        self.log("[+] Step 3/9: HTTP Security Headers & Tech Fingerprint Inspection...")
        headers_info = self._audit_headers()

        # Step 4: CORS REST API Misconfiguration
        self.log("[+] Step 4/9: WordPress REST API CORS & Credentials Probing...")
        cors_info = self._audit_cors()

        # Step 5: WordPress User Enumeration & XML-RPC
        self.log("[+] Step 5/9: User Enumeration & XML-RPC Multicall Testing...")
        wp_info = self._audit_wordpress()

        # Step 6: Sensitive File Exposure
        self.log("[+] Step 6/9: Sensitive Configuration & Backup Files Probe...")
        files_info = self._audit_sensitive_files()

        # Step 7: Form PII & Submission Security
        self.log("[+] Step 7/9: HTML DOM Form Inspection & PII Leakage Check...")
        forms_info = self._audit_forms_and_dom()

        # Step 8: DNS & Email Anti-Spoofing (DMARC, SPF, CAA)
        self.log("[+] Step 8/9: DNS Domain Security & DMARC Spoofing Assessment...")
        dns_info = self._audit_dns()

        # Step 9: Headless Browser / Resource Check
        self.log("[+] Step 9/9: Client-Side Headless Browser Diagnostics...")
        browser_info = self._audit_browser_checks()

        # Calculate Scores
        score, grade, counts = self._calculate_scores()
        self.log(f"\n[*] Audit Completed! Score: {score}/100 | Grade: {grade}")
        self.log(f"[*] Findings: {counts['critical']} Critical | {counts['high']} High | {counts['medium']} Med | {counts['low']} Low | {counts['passed']} Passed")

        # Generate Code Patches
        patches = self._generate_patches(ip_address, headers_info, wp_info)

        # Generate PDF Report
        pdf_path, pdf_filename = self._generate_pdf(score, grade, counts, ip_address, headers_info, patches)
        if pdf_path:
            self.log(f"[OK] Security PDF Report generated: {pdf_filename}")

        result_data = {
            "url": self.target_url,
            "domain": self.domain,
            "ip_address": ip_address,
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "score": score,
            "grade": grade,
            "counts": counts,
            "findings": self.findings,
            "tls_info": tls_info,
            "headers_info": headers_info,
            "dns_info": dns_info,
            "patches": patches,
            "pdf_path": pdf_path,
            "pdf_filename": pdf_filename,
        }
        return result_data

    # -----------------------------------------------------------------------
    # Probing Steps
    # -----------------------------------------------------------------------
    def _resolve_ip(self) -> str:
        try:
            ip = socket.gethostbyname(self.domain)
            self.log(f"    Resolved IP: {ip}")
            return ip
        except Exception as e:
            self.log(f"    DNS resolution error: {e}")
            return "Unknown"

    def _audit_tls(self) -> dict:
        res = {"version": "Unknown", "cipher": "Unknown", "cert_valid": False, "issuer": "", "expires": ""}
        if self.scheme != "https":
            self.add_finding("SEC-TLS-01", "critical", "Insecure Plaintext HTTP Scheme", self.target_url,
                             "Site loaded over unencrypted HTTP, exposing all credentials and traffic to eavesdropping.",
                             "Enforce HTTPS with 301 redirection and HSTS.")
            return res

        ctx = ssl.create_default_context()
        try:
            with socket.create_connection((self.domain, 443), timeout=6) as sock:
                with ctx.wrap_socket(sock, server_hostname=self.domain) as ssock:
                    res["version"] = ssock.version()
                    res["cipher"] = ssock.cipher()[0] if ssock.cipher() else ""
                    cert = ssock.getpeercert()
                    res["cert_valid"] = True
                    res["expires"] = cert.get("notAfter", "")
                    issuer_dict = dict(x[0] for x in cert.get("issuer", ()))
                    res["issuer"] = issuer_dict.get("organizationName", issuer_dict.get("commonName", "Unknown CA"))

            self.log(f"    TLS Protocol: {res['version']} | Cipher: {res['cipher']}")
            self.log(f"    Certificate Issuer: {res['issuer']} | Expires: {res['expires']}")
            self.add_finding("SEC-TLS-02", "passed", f"Modern Transport Encryption ({res['version']})", "HTTPS:443",
                             f"Strong TLS encryption active with cipher {res['cipher']}.",
                             "Maintain current certificate renewal automation.", status="passed")
        except Exception as e:
            self.log(f"    SSL Error: {e}")
            self.add_finding("SEC-TLS-03", "high", "SSL/TLS Handshake Anomaly", "HTTPS:443",
                             f"Failed to cleanly verify SSL certificate: {str(e)}",
                             "Check certificate chain and server TLS configuration.")

        # Test legacy TLS rejection
        legacy_supported = False
        for proto, name in [(getattr(ssl, 'PROTOCOL_TLSv1', None), 'TLS 1.0'), (getattr(ssl, 'PROTOCOL_TLSv1_1', None), 'TLS 1.1')]:
            if proto:
                try:
                    pctx = ssl.SSLContext(proto)
                    with socket.create_connection((self.domain, 443), timeout=4) as s:
                        with pctx.wrap_socket(s, server_hostname=self.domain):
                            legacy_supported = True
                            self.add_finding("SEC-TLS-04", "high", f"Insecure Legacy Protocol Enabled ({name})", "HTTPS:443",
                                             f"{name} is vulnerable to BEAST/POODLE attacks and deprecated.",
                                             f"Disable {name} on web server and load balancer.")
                except Exception:
                    pass

        if not legacy_supported:
            self.add_finding("SEC-TLS-05", "passed", "Legacy Insecure Protocols Disabled (TLS 1.0/1.1)", "HTTPS:443",
                             "Legacy TLS 1.0 and 1.1 protocols are correctly rejected.",
                             "Maintain modern TLS 1.2 and 1.3 only.", status="passed")

        return res

    def _audit_headers(self) -> dict:
        res = {"server": "", "powered_by": "", "platform": "", "headers": {}}
        import urllib.request
        req = urllib.request.Request(self.target_url, headers={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) InersiaLabAudit/2.0"})
        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE

        try:
            with urllib.request.urlopen(req, context=ctx, timeout=8) as resp:
                headers = {k.lower(): v for k, v in resp.headers.items()}
                res["headers"] = headers
                res["server"] = headers.get("server", "")
                res["powered_by"] = headers.get("x-powered-by", "")
                res["platform"] = headers.get("platform", "")

                # Information disclosure
                disclosures = []
                if res["powered_by"]:
                    disclosures.append(f"X-Powered-By: {res['powered_by']}")
                if res["server"] and not res["server"].lower() in ("cloudflare", ""):
                    disclosures.append(f"Server: {res['server']}")
                if headers.get("platform"):
                    disclosures.append(f"platform: {headers['platform']}")
                if headers.get("panel"):
                    disclosures.append(f"panel: {headers['panel']}")

                if disclosures:
                    self.log(f"    [!] Information disclosure found: {', '.join(disclosures)}")
                    self.add_finding("SEC-HDR-01", "medium", "Server Fingerprint & Information Disclosure", "HTTP Headers",
                                     f"Headers leak infrastructure technologies: {', '.join(disclosures)}. Gives attackers precise software fingerprints.",
                                     "Unset 'X-Powered-By', 'Server', and hosting provider headers in web server config.")
                else:
                    self.add_finding("SEC-HDR-02", "passed", "No Server Fingerprints Disclosed", "HTTP Headers",
                                     "Server does not leak framework or software versions in HTTP headers.",
                                     "Keep server signature masking active.", status="passed")

                # HSTS
                hsts = headers.get("strict-transport-security", "")
                if not hsts:
                    self.add_finding("SEC-HDR-03", "high", "Missing Strict-Transport-Security (HSTS)", "HTTP Headers",
                                     "Browsers are not instructed to strictly enforce HTTPS, opening risk for SSL stripping.",
                                     "Add 'Strict-Transport-Security: max-age=31536000; includeSubDomains; preload'.")
                elif "preload" not in hsts.lower():
                    self.add_finding("SEC-HDR-04", "low", "HSTS Missing Preload Directive", "HTTP Headers",
                                     f"HSTS present ({hsts}) but missing 'preload' flag for browser inclusion lists.",
                                     "Add '; preload' to the Strict-Transport-Security header.")
                else:
                    self.add_finding("SEC-HDR-05", "passed", "Strict-Transport-Security (HSTS Preloaded)", "HTTP Headers",
                                     f"HSTS configured with preload ({hsts}).", "Maintain current policy.", status="passed")

                # Content-Security-Policy
                csp = headers.get("content-security-policy", "")
                if not csp:
                    self.add_finding("SEC-HDR-06", "high", "Missing Content-Security-Policy (CSP)", "HTTP Headers",
                                     "No CSP defined, leaving website vulnerable to Cross-Site Scripting (XSS) and code injection.",
                                     "Deploy a Content-Security-Policy header restricting script and object sources.")
                elif csp.strip() == "upgrade-insecure-requests":
                    self.add_finding("SEC-HDR-07", "medium", "Inadequate Content Security Policy (Minimal)", "HTTP Headers",
                                     f"CSP only contains 'upgrade-insecure-requests'. Lacks default-src, script-src, and frame-ancestors restrictions.",
                                     "Expand CSP to restrict executable scripts, frames, and resource origins.")
                else:
                    self.add_finding("SEC-HDR-08", "passed", "Content-Security-Policy Active", "HTTP Headers",
                                     "Content Security Policy is enforced.", "Review CSP periodically for script policy tightening.", status="passed")

                # X-Frame-Options / Clickjacking
                xfo = headers.get("x-frame-options", "")
                if not xfo and "frame-ancestors" not in csp:
                    self.add_finding("SEC-HDR-09", "medium", "Missing Clickjacking Protection (X-Frame-Options)", "HTTP Headers",
                                     "Site can be embedded in malicious iframes, enabling UI redress and clickjacking attacks.",
                                     "Set 'X-Frame-Options: SAMEORIGIN' or CSP 'frame-ancestors 'self''.")
                else:
                    self.add_finding("SEC-HDR-10", "passed", "Clickjacking Protection Configured", "HTTP Headers",
                                     f"Frame embedding restricted via {xfo or 'CSP frame-ancestors'}.", "Maintain policy.", status="passed")

                # X-Content-Type-Options
                xcto = headers.get("x-content-type-options", "")
                if xcto.lower() != "nosniff":
                    self.add_finding("SEC-HDR-11", "low", "Missing X-Content-Type-Options: nosniff", "HTTP Headers",
                                     "Browsers may MIME-sniff responses, causing CSS/image files to be executed as scripts.",
                                     "Add 'X-Content-Type-Options: nosniff'.")
                else:
                    self.add_finding("SEC-HDR-12", "passed", "X-Content-Type-Options (nosniff) Active", "HTTP Headers",
                                     "MIME-type sniffing is blocked.", "Maintain nosniff header.", status="passed")

                # Referrer-Policy
                ref = headers.get("referrer-policy", "")
                if not ref:
                    self.add_finding("SEC-HDR-13", "low", "Missing Referrer-Policy", "HTTP Headers",
                                     "Referrer headers may leak full URLs with query parameters to third-party domains.",
                                     "Set 'Referrer-Policy: strict-origin-when-cross-origin'.")
                else:
                    self.add_finding("SEC-HDR-14", "passed", f"Referrer-Policy Defined ({ref})", "HTTP Headers",
                                     f"Referrer-Policy configured: {ref}.", "Maintain policy.", status="passed")

        except Exception as e:
            self.log(f"    Headers error: {e}")
        return res

    def _audit_cors(self) -> dict:
        import urllib.request
        res = {"vulnerable": False, "allow_origin": "", "allow_credentials": ""}
        cors_url = f"{self.scheme}://{self.domain}/wp-json/"
        evil_origin = "https://evil-security-audit.com"

        req = urllib.request.Request(cors_url, headers={
            "Origin": evil_origin,
            "User-Agent": "Mozilla/5.0 InersiaLabSecurityAudit/2.0"
        })
        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE

        try:
            with urllib.request.urlopen(req, context=ctx, timeout=7) as resp:
                ao = resp.headers.get("Access-Control-Allow-Origin", "")
                ac = resp.headers.get("Access-Control-Allow-Credentials", "")
                res["allow_origin"] = ao
                res["allow_credentials"] = ac

                self.log(f"    CORS Probe on /wp-json/: Origin={ao} | Credentials={ac}")
                if ao == evil_origin and str(ac).lower() == "true":
                    res["vulnerable"] = True
                    self.add_finding("SEC-CORS-01", "critical", "CORS Misconfiguration: Reflected Origin with Credentials", "/wp-json/*",
                                     f"Server dynamically reflects arbitrary Origin ({evil_origin}) with 'Access-Control-Allow-Credentials: true'. Malicious third-party sites can execute authenticated cross-origin reads on behalf of logged-in administrators.",
                                     "Whitelist only explicit company domains in 'rest_pre_serve_request' filter and forbid credentials on wildcard/arbitrary origins.")
                elif ao == "*" and str(ac).lower() == "true":
                    res["vulnerable"] = True
                    self.add_finding("SEC-CORS-02", "critical", "Insecure CORS: Wildcard Origin with Credentials", "/wp-json/*",
                                     "Server attempts to allow all origins with credentials, creating severe cross-origin authorization flaws.",
                                     "Disallow credentials when using wildcard origins.")
                else:
                    self.add_finding("SEC-CORS-03", "passed", "REST API CORS Secure", "/wp-json/*",
                                     "REST API does not reflect arbitrary origins alongside credentials.",
                                     "Maintain strict origin whitelist.", status="passed")
        except Exception as e:
            self.log(f"    CORS check notice: {e}")
            self.add_finding("SEC-CORS-04", "passed", "REST API Not Publicly Reflective", "/wp-json/*",
                             "CORS reflection probe was rejected or endpoint not present.", "Maintain configuration.", status="passed")
        return res

    def _audit_wordpress(self) -> dict:
        import urllib.request
        res = {"xmlrpc_enabled": False, "users_exposed": []}
        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE

        # 1. XML-RPC
        xml_url = f"{self.scheme}://{self.domain}/xmlrpc.php"
        payload = b'<?xml version="1.0"?><methodCall><methodName>system.listMethods</methodName><params></params></methodCall>'
        req = urllib.request.Request(xml_url, data=payload, headers={"Content-Type": "text/xml", "User-Agent": "Mozilla/5.0"})
        try:
            with urllib.request.urlopen(req, context=ctx, timeout=7) as resp:
                body = resp.read().decode("utf-8", errors="ignore")
                if "system.multicall" in body:
                    res["xmlrpc_enabled"] = True
                    self.log("    [!] XML-RPC is active with system.multicall!")
                    self.add_finding("SEC-WP-01", "high", "Active XML-RPC API (system.multicall & Pingback)", "/xmlrpc.php",
                                     "Exposed XML-RPC API enables password brute-force amplification (hundreds of guesses per request) and participation in distributed DDoS reflection attacks.",
                                     "Block /xmlrpc.php in .htaccess and add 'xmlrpc_enabled' => false filter in functions.php.")
        except Exception:
            self.add_finding("SEC-WP-02", "passed", "XML-RPC Endpoint Blocked / Disabled", "/xmlrpc.php",
                             "XML-RPC API is inaccessible or blocked.", "Maintain XML-RPC block.", status="passed")

        # 2. User Enumeration via REST API
        users_url = f"{self.scheme}://{self.domain}/wp-json/wp/v2/users"
        ureq = urllib.request.Request(users_url, headers={"User-Agent": "Mozilla/5.0"})
        try:
            with urllib.request.urlopen(ureq, context=ctx, timeout=7) as uresp:
                if uresp.status == 200:
                    data = json.loads(uresp.read().decode("utf-8", errors="ignore"))
                    if isinstance(data, list) and len(data) > 0:
                        res["users_exposed"] = [u.get("slug") or u.get("name") for u in data]
                        self.log(f"    [!] Exposed users via REST: {res['users_exposed']}")
                        self.add_finding("SEC-WP-03", "critical", "Unauthenticated Sensitive User Enumeration", "/wp-json/wp/v2/users",
                                         f"Publicly exposes administrator usernames/slugs: {', '.join(res['users_exposed'])}. Provides attackers with the exact login names needed for brute-force attacks.",
                                         "Unset '/wp/v2/users' endpoints for non-admin users in functions.php and block ?author=1 queries in .htaccess.")
        except Exception:
            self.add_finding("SEC-WP-04", "passed", "REST API User Enumeration Blocked", "/wp-json/wp/v2/users",
                             "User enumeration endpoint is protected or returns 401/403.", "Maintain access restrictions.", status="passed")

        # 3. WordPress Login Portal
        login_url = f"{self.scheme}://{self.domain}/wp-login.php"
        lreq = urllib.request.Request(login_url, headers={"User-Agent": "Mozilla/5.0"})
        try:
            with urllib.request.urlopen(lreq, context=ctx, timeout=7) as lresp:
                if lresp.status == 200:
                    self.add_finding("SEC-WP-05", "medium", "Exposed WordPress Login Portal (/wp-login.php)", "/wp-login.php",
                                     "Default admin login portal is publicly reachable without IP restriction, MFA challenge, or slug obfuscation.",
                                     "Obfuscate the login URL with a security plugin (e.g. WPS Hide Login) and enforce 2-Factor Authentication.")
        except Exception:
            pass

        return res

    def _audit_sensitive_files(self) -> dict:
        import urllib.request
        import urllib.error
        res = {"exposed_files": []}
        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE

        sensitive_paths = [
            ("/readme.html", "WordPress Readme File (Version Disclosure)", "medium"),
            ("/license.txt", "WordPress License File (Version Fingerprint)", "low"),
            ("/.env", "Environment Variables File (.env)", "critical"),
            ("/.git/HEAD", "Git Repository Metadata (.git)", "critical"),
            ("/wp-config.php.bak", "WordPress Database Config Backup", "critical"),
            ("/wp-content/debug.log", "WordPress Debug Log", "high"),
        ]

        for path, label, sev in sensitive_paths:
            u = f"{self.scheme}://{self.domain}{path}"
            req = urllib.request.Request(u, headers={"User-Agent": "Mozilla/5.0"})
            try:
                with urllib.request.urlopen(req, context=ctx, timeout=5) as r:
                    if r.status == 200 and len(r.read()) > 20:
                        res["exposed_files"].append(path)
                        self.log(f"    [!] Exposed file: {path} (Status 200)")
                        self.add_finding(f"SEC-FILE-{path.replace('/', '').replace('.', '')[:8]}", sev,
                                         f"Publicly Accessible Sensitive File: {path}", path,
                                         f"{label} is publicly accessible over HTTP, exposing system internals.",
                                         f"Block access to {path} in .htaccess via FilesMatch directive.")
            except urllib.error.HTTPError as e:
                if e.code in (403, 404):
                    pass
            except Exception:
                pass

        if not any(f in res["exposed_files"] for f in ("/.env", "/.git/HEAD", "/wp-config.php.bak")):
            self.add_finding("SEC-FILE-00", "passed", "Sensitive Configuration Files Protected", "Root Directory",
                             "Configuration files (.env, .git, wp-config backups) are strictly blocked with 403/404.",
                             "Keep server access restrictions active.", status="passed")

        return res

    def _audit_forms_and_dom(self) -> dict:
        import urllib.request
        res = {"generator_leaks": [], "insecure_forms": []}
        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE

        req = urllib.request.Request(self.target_url, headers={"User-Agent": "Mozilla/5.0"})
        try:
            with urllib.request.urlopen(req, context=ctx, timeout=8) as resp:
                html = resp.read().decode("utf-8", errors="ignore")

                # Generator tags
                generators = re.findall(r'<meta[^>]*name=[\'"]generator[\'"][^>]*content=[\'"]([^\'"]*)[\'"]', html, re.I)
                if generators:
                    res["generator_leaks"] = generators
                    self.log(f"    [!] Generator meta tags leaked: {generators}")
                    self.add_finding("SEC-DOM-01", "medium", "CMS & Page Builder Version Leaks in Meta Tags", "<head> HTML",
                                     f"HTML leaks exact framework versions: {', '.join(generators)}.",
                                     "Remove 'wp_generator' action and Elementor generator tags in functions.php.")
                else:
                    self.add_finding("SEC-DOM-02", "passed", "No Version Generator Tags", "<head> HTML",
                                     "HTML source does not expose CMS version generator tags.", "Maintain tag removal.", status="passed")

                # Forms inspection
                forms = re.findall(r'<form\b([^>]*)>(.*?)</form>', html, re.DOTALL | re.I)
                for attrs, inner in forms:
                    method_m = re.search(r'method=[\'"]([^\'"]*)[\'"]', attrs, re.I)
                    id_m = re.search(r'id=[\'"]([^\'"]*)[\'"]', attrs, re.I)
                    form_id = id_m.group(1) if id_m else "unknown-form"
                    method = method_m.group(1).lower() if method_m else "get"  # HTML default is GET!

                    # Check if form collects sensitive fields (email, phone, message)
                    has_pii = any(term in inner.lower() for term in ("email", "phone", "first_name", "last_name", "message", "password"))
                    if has_pii and method == "get":
                        res["insecure_forms"].append(form_id)
                        self.log(f"    [!] Form #{form_id} uses GET method with sensitive user fields!")
                        self.add_finding("SEC-DOM-03", "critical", "Sensitive PII Leaked via HTTP GET Form Submission", f"#{form_id}",
                                         "Contact form uses method='get', appending user names, phone numbers, and emails as plaintext URL query parameters. PII is permanently logged in browser history, server logs, proxies, and analytics referrers.",
                                         "Switch form method from 'get' to 'post' and implement secure AJAX submission.")

                    # Novalidate check
                    if "novalidate" in attrs.lower():
                        self.add_finding("SEC-DOM-04", "low", f"Client-Side Validation Disabled on #{form_id}", f"#{form_id}",
                                         "Form specifies 'novalidate' attribute. If client-side JavaScript validation is absent, blank or spam submissions bypass verification.",
                                         "Attach robust JavaScript input validation before dispatching submission.")

        except Exception as e:
            self.log(f"    DOM check notice: {e}")
        return res

    def _audit_dns(self) -> dict:
        import urllib.request
        res = {"spf": "", "dmarc": "", "caa": "", "dnssec": False}

        # Query DOH via Google
        def query_doh(name, qtype):
            try:
                u = f"https://dns.google/resolve?name={quote(name)}&type={qtype}"
                req = urllib.request.Request(u, headers={"User-Agent": "Mozilla/5.0 InersiaLabAudit/2.0"})
                with urllib.request.urlopen(req, timeout=5) as r:
                    data = json.loads(r.read().decode("utf-8"))
                    answers = data.get("Answer", [])
                    return [a.get("data", "").strip('"') for a in answers]
            except Exception:
                return []

        # 1. SPF
        spf_records = [r for r in query_doh(self.domain, "TXT") if "v=spf1" in r]
        if spf_records:
            res["spf"] = spf_records[0]
            self.log(f"    SPF Record: {res['spf']}")
            self.add_finding("SEC-DNS-01", "passed", "SPF Domain Record Configured", f"TXT {self.domain}",
                             f"SPF policy found: {res['spf']}", "Maintain SPF IP alignment.", status="passed")
        else:
            self.add_finding("SEC-DNS-02", "high", "Missing SPF Email Authentication Record", f"TXT {self.domain}",
                             "Domain lacks an SPF record, allowing unauthorized servers to spoof emails from your domain.",
                             "Configure an SPF TXT record in your DNS zone.")

        # 2. DMARC
        dmarc_records = [r for r in query_doh(f"_dmarc.{self.domain}", "TXT") if "v=DMARC1" in r]
        if not dmarc_records:
            self.add_finding("SEC-DNS-03", "critical", "Missing DMARC Anti-Spoofing Policy", f"TXT _dmarc.{self.domain}",
                             "No DMARC record exists. Threat actors can send fraudulent phishing emails pretending to be your company.",
                             "Deploy a DMARC record with 'p=quarantine' or 'p=reject'.")
        else:
            res["dmarc"] = dmarc_records[0]
            self.log(f"    DMARC Record: {res['dmarc']}")
            if "p=none" in res["dmarc"].lower():
                self.add_finding("SEC-DNS-04", "high", "Inadequate DMARC Email Protection (p=none)", f"TXT _dmarc.{self.domain}",
                                 "DMARC policy is set to 'p=none' (monitoring only). Receiving email servers will not reject or quarantine spoofed emails sent using your brand name.",
                                 "Upgrade DMARC policy to 'p=quarantine' or 'p=reject' and add a 'rua=mailto:...' reporting inbox.")
            else:
                self.add_finding("SEC-DNS-05", "passed", "Enforced DMARC Anti-Spoofing Policy", f"TXT _dmarc.{self.domain}",
                                 f"DMARC enforcement active: {res['dmarc']}", "Monitor DMARC aggregate reports.", status="passed")

        # 3. CAA
        caa_records = query_doh(self.domain, "CAA")
        if caa_records:
            res["caa"] = ", ".join(caa_records)
            self.add_finding("SEC-DNS-06", "passed", "Certificate Authority Authorization (CAA) Configured", f"CAA {self.domain}",
                             f"CAA restrictions active: {res['caa']}", "Maintain CAA records.", status="passed")
        else:
            self.add_finding("SEC-DNS-07", "low", "Missing CAA DNS Record", f"CAA {self.domain}",
                             "No CAA records defined. Any public Certificate Authority can issue SSL certificates for your domain.",
                             "Add CAA records restricting issuance to your designated provider (e.g. 0 issue \"letsencrypt.org\").")

        return res

    def _audit_browser_checks(self) -> dict:
        res = {"console_errors": [], "broken_resources": [], "unsafe_links": []}
        
        # Check reverse tabnabbing and 404 resource via Playwright if available
        try:
            from playwright.sync_api import sync_playwright
            playwright_paths = [
                os.path.expanduser("~/.gemini/config/skills/claude-seo/ms-playwright"),
                os.path.expanduser("~/.claude/skills/seo/ms-playwright"),
            ]
            browser_path = None
            for pw_path in playwright_paths:
                if os.path.exists(pw_path):
                    for dirpath, dirnames, filenames in os.walk(pw_path):
                        for fn in filenames:
                            if fn in ("chrome.exe", "chromium.exe", "chromium"):
                                browser_path = os.path.join(dirpath, fn)
                                break
                        if browser_path:
                            break
                if browser_path:
                    break

            with sync_playwright() as p:
                launch_args = {"headless": True}
                if browser_path:
                    launch_args["executable_path"] = browser_path
                browser = p.chromium.launch(**launch_args)
                page = browser.new_page(viewport={"width": 1440, "height": 900})

                page.on("console", lambda msg: res["console_errors"].append(msg.text) if msg.type == "error" else None)
                page.on("response", lambda resp: (
                    res["broken_resources"].append({"url": resp.url, "status": resp.status})
                    if resp.status >= 400 and not "favicon.ico" in resp.url else None
                ))

                page.goto(self.target_url, wait_until="networkidle", timeout=20000)

                # Check target=_blank without rel=noopener/noreferrer
                unsafe_blanks = page.eval_on_selector_all("a[target='_blank']", """els => els.map(e => ({
                    text: e.innerText.trim().substring(0, 30),
                    href: e.href,
                    rel: e.rel
                })).filter(e => !e.rel.includes('noopener') || !e.rel.includes('noreferrer'))""")

                if unsafe_blanks:
                    res["unsafe_links"] = unsafe_blanks
                    self.add_finding("SEC-DOM-05", "low", "Reverse Tabnabbing Risk on Links (target='_blank')", "<a target='_blank'>",
                                     f"Found {len(unsafe_blanks)} link(s) opening new tabs without 'rel=\"noopener noreferrer\"'. Allows opened destination to access window.opener.",
                                     "Add rel=\"noopener noreferrer\" to all target=\"_blank\" anchor tags.")

                if res["broken_resources"]:
                    broken_url = res["broken_resources"][0]["url"]
                    self.add_finding("SEC-NET-01", "low", "Broken Page Resource (404 / 500)", broken_url,
                                     f"Resource failed to load with status {res['broken_resources'][0]['status']}, generating browser console errors.",
                                     "Update reference or upload missing resource file.")

                browser.close()
        except Exception as e:
            self.log(f"    Browser audit note: {e}")

        return res

    # -----------------------------------------------------------------------
    # Score Calculation
    # -----------------------------------------------------------------------
    def _calculate_scores(self) -> tuple:
        counts = {"critical": 0, "high": 0, "medium": 0, "low": 0, "passed": 0}
        score = 100

        for f in self.findings:
            sev = f["severity"]
            if sev in counts:
                counts[sev] += 1
            if sev == "critical":
                score -= 25
            elif sev == "high":
                score -= 15
            elif sev == "medium":
                score -= 8
            elif sev == "low":
                score -= 3

        score = max(5, min(100, score))
        if score >= 90:
            grade = "A (Excellent)"
        elif score >= 80:
            grade = "B (Good)"
        elif score >= 70:
            grade = "C+ (Needs Immediate Attention)"
        elif score >= 60:
            grade = "D (High Risk)"
        else:
            grade = "F (Critical Vulnerabilities Detected)"

        return score, grade, counts

    # -----------------------------------------------------------------------
    # Code Patch Generation
    # -----------------------------------------------------------------------
    def _generate_patches(self, ip_address: str, headers_info: dict, wp_info: dict) -> dict:
        htaccess_code = """# ==============================================================================
# INERSIALAB PRODUCTION SECURITY HARDENING (.htaccess)
# Target: {domain} | Generated: {date}
# ==============================================================================

# 1. Block XML-RPC Completely (Mitigate Brute Force & DDoS Reflection)
<Files xmlrpc.php>
    Order Deny,Allow
    Deny from all
</Files>

# 2. Block Author / User Enumeration Scanning (?author=1)
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{QUERY_STRING} ^author=([0-9]+) [NC]
    RewriteRule .* - [F,L]
</IfModule>

# 3. Block Sensitive Files from Public HTTP Access
<FilesMatch "^(readme\\.html|license\\.txt|wp-config.*|\\.env|\\.git|debug\\.log)">
    Order Deny,Allow
    Deny from all
</FilesMatch>

# 4. Strip Server Fingerprints & Enforce Enterprise Security Headers
<IfModule mod_headers.c>
    Header unset X-Powered-By
    Header always unset X-Powered-By
    Header unset Server
    
    Header set X-Content-Type-Options "nosniff"
    Header set X-Frame-Options "SAMEORIGIN"
    Header set Referrer-Policy "strict-origin-when-cross-origin"
    Header set Permissions-Policy "camera=(), microphone=(), geolocation=(), payment=()"
    Header set Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
    Header set Content-Security-Policy "default-src 'self' https: data: 'unsafe-inline' 'unsafe-eval'; frame-ancestors 'self';"
</IfModule>""".replace("{domain}", self.domain).replace("{date}", datetime.now().strftime('%Y-%m-%d'))

        functions_code = f"""<?php
// ==============================================================================
// INERSIALAB APPLICATION SECURITY & PRIVACY PATCHES (functions.php)
// Target: {self.domain} | Generated: {datetime.now().strftime('%Y-%m-%d')}
// ==============================================================================

// 1. Fix Critical CORS Flaw: Whitelist Origin & Forbid Credentials on Arbitrary Domains
add_filter('rest_pre_serve_request', function($value) {{
    $origin = get_http_origin();
    $allowed_origins = [
        'https://{self.domain}',
        'https://www.{self.domain}'
    ];
    if ($origin && in_array($origin, $allowed_origins, true)) {{
        header('Access-Control-Allow-Origin: ' . $origin);
        header('Access-Control-Allow-Credentials: true');
    }} else {{
        header('Access-Control-Allow-Origin: *');
        header('Access-Control-Allow-Credentials: false');
    }}
    return $value;
}});

// 2. Block Public User Enumeration via REST API (/wp-json/wp/v2/users)
add_filter('rest_endpoints', function($endpoints) {{
    if (isset($endpoints['/wp/v2/users']) && !current_user_can('list_users')) {{
        unset($endpoints['/wp/v2/users']);
    }}
    if (isset($endpoints['/wp/v2/users/(?P<id>[\\d]+)']) && !current_user_can('list_users')) {{
        unset($endpoints['/wp/v2/users/(?P<id>[\\d]+)']);
    }}
    return $endpoints;
}});

// 3. Remove WordPress and Elementor Generator Meta Tags
remove_action('wp_head', 'wp_generator');
add_filter('the_generator', '__return_empty_string');
add_action('init', function() {{
    if (class_exists('\\\\Elementor\\\\Plugin')) {{
        remove_action('wp_head', [\\\\Elementor\\\\Plugin::$instance->frontend, 'print_generator_tag']);
    }}
}});

// 4. Disable XML-RPC Services Programmatically
add_filter('xmlrpc_enabled', '__return_false');
add_filter('xmlrpc_methods', '__return_empty_array');"""

        form_code = f"""<!-- 1. HTML Template: Change method='get' to method='post' and include nonce -->
<form id="contact-form" method="post" action="">
    <?php wp_nonce_field('site_contact_action', 'site_contact_nonce'); ?>
    <div style="display:none !important;"><input type="text" name="website_hp" tabindex="-1" autocomplete="off"></div>
    <!-- Input fields... -->
</form>

<!-- 2. Theme JavaScript: Client-side Validation & Asynchronous POST Handler -->
<script>
document.getElementById('contact-form').addEventListener('submit', function(e) {{
    e.preventDefault();
    const form = this;
    const email = (form.querySelector('input[type="email"]') || {{}}).value || '';
    if (!email.trim()) {{
        alert('Please enter a valid email address.');
        return;
    }}
    const formData = new FormData(form);
    formData.append('action', 'site_submit_contact');

    fetch('/wp-admin/admin-ajax.php', {{ method: 'POST', body: formData }})
    .then(res => res.json())
    .then(data => {{
        if (data.success) {{
            form.innerHTML = '<div style="padding:15px; background:#dcfce7; color:#15803d; border-radius:6px;">Thank you! Your inquiry has been submitted securely.</div>';
        }} else {{
            alert(data.data.message || 'Submission failed. Please try again.');
        }}
    }})
    .catch(() => alert('Network error. Please try again.'));
}});
</script>"""

        dns_records = [
            {"type": "TXT", "host": "_dmarc", "value": f"v=DMARC1; p=quarantine; rua=mailto:dmarc@{self.domain}; pct=100; aspf=r", "purpose": "Quarantines spoofed/phishing emails sent pretending to be your domain."},
            {"type": "CAA", "host": "@", "value": "0 issue \"letsencrypt.org\"\n0 issuewild \";\"", "purpose": "Restricts SSL certificate issuance strictly to authorized CAs."},
        ]

        master_prompt = f"""================================================================================
MASTER AI FIX PROMPT: REMEDIATE SECURITY & SERVER FLAWS ON {self.domain}
================================================================================

Role: You are a Senior WordPress Full-Stack Engineer and Security Hardening Specialist.
Task: Remediate all critical, high, and medium security vulnerabilities detected on {self.domain}.

1. FIX REST API CORS MISCONFIGURATION (/wp-json/):
   - In functions.php, hook into 'rest_pre_serve_request' filter.
   - Stop dynamically reflecting untrusted Origin headers with 'Access-Control-Allow-Credentials: true'.
   - Whitelist only 'https://{self.domain}' and 'https://www.{self.domain}' for authenticated CORS.
   - For all other origins, return 'Access-Control-Allow-Origin: *' with 'Access-Control-Allow-Credentials: false'.

2. BLOCK USER ENUMERATION & INFORMATION LEAKS:
   - In functions.php, unset '/wp/v2/users' endpoints for non-admin users.
   - In .htaccess, add a RewriteRule that returns 403 Forbidden for queries matching 'author=([0-9]+)'.
   - Block public HTTP access to /readme.html, /license.txt, and /wp-content/debug.log.
   - Strip 'X-Powered-By' and 'Server' response headers using mod_headers.
   - Remove 'wp_generator' and Elementor generator meta tags from HTML head output.

3. REMEDIATE CONTACT FORM PII EXPOSURE:
   - On contact forms, change method attribute from 'get' to 'post'.
   - Attach client-side JavaScript validation preventing empty submissions.
   - Implement an AJAX POST endpoint with nonce validation and honeypot checking.

4. DISABLE XML-RPC SERVICE (/xmlrpc.php):
   - In .htaccess, add <Files xmlrpc.php> Order Deny,Allow Deny from all </Files>.
   - In functions.php, add filters: 'xmlrpc_enabled' => false and 'xmlrpc_methods' => empty array.

5. HARDEN DNS & HEADERS:
   - In DNS, update DMARC record to: 'v=DMARC1; p=quarantine; rua=mailto:admin@{self.domain}; pct=100; aspf=r'.
   - Add CAA record: 0 issue "letsencrypt.org".
   - Add 'preload' directive to Strict-Transport-Security header.

Verify all changes using curl and browser testing to ensure zero functional regressions."""

        return {
            "htaccess": htaccess_code,
            "functions_php": functions_code,
            "contact_form": form_code,
            "dns": dns_records,
            "master_prompt": master_prompt,
        }

    # -----------------------------------------------------------------------
    # PDF Report Builder
    # -----------------------------------------------------------------------
    def _generate_pdf(self, score: int, grade: str, counts: dict, ip_address: str, headers_info: dict, patches: dict) -> tuple:
        if not REPORTLAB_AVAILABLE:
            return None, None

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_domain = self.domain.replace(".", "_")
        pdf_filename = f"Security_Audit_{safe_domain}_{timestamp}.pdf"
        pdf_path = os.path.join(DOWNLOADS_DIR, pdf_filename)

        # Also fallback or alias
        primary_name = f"{self.domain}_Security_Audit_Report.pdf"
        primary_path = os.path.join(DOWNLOADS_DIR, primary_name)

        try:
            doc = SimpleDocTemplate(
                pdf_path,
                pagesize=A4,
                leftMargin=36,
                rightMargin=36,
                topMargin=42,
                bottomMargin=46
            )

            styles = getSampleStyleSheet()
            title_style = ParagraphStyle('DocTitle', parent=styles['Heading1'], fontName='Helvetica-Bold', fontSize=18, leading=22, textColor=colors.HexColor("#111827"), spaceAfter=3)
            subtitle_style = ParagraphStyle('DocSubTitle', parent=styles['Normal'], fontName='Helvetica', fontSize=9, leading=13, textColor=colors.HexColor("#4b5563"), spaceAfter=10)
            h1_style = ParagraphStyle('SectionH1', parent=styles['Heading2'], fontName='Helvetica-Bold', fontSize=12, leading=15, textColor=colors.HexColor("#111827"), spaceBefore=10, spaceAfter=6, keepWithNext=True)
            h2_style = ParagraphStyle('SectionH2', parent=styles['Heading3'], fontName='Helvetica-Bold', fontSize=9.5, leading=13, textColor=colors.HexColor("#1f2937"), spaceBefore=7, spaceAfter=3, keepWithNext=True)
            body_style = ParagraphStyle('BodyDark', parent=styles['Normal'], fontName='Helvetica', fontSize=7.5, leading=10.5, textColor=colors.HexColor("#1f2937"))
            body_bold = ParagraphStyle('BodyBold', parent=body_style, fontName='Helvetica-Bold')
            code_style = ParagraphStyle('CodeSnippet', parent=styles['Normal'], fontName='Courier', fontSize=6.5, leading=8.5, textColor=colors.HexColor("#111827"))

            badge_crit = ParagraphStyle('BC', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=7, leading=9, textColor=colors.HexColor("#991b1b"))
            badge_high = ParagraphStyle('BH', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=7, leading=9, textColor=colors.HexColor("#c2410c"))
            badge_med = ParagraphStyle('BM', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=7, leading=9, textColor=colors.HexColor("#b45309"))
            badge_low = ParagraphStyle('BL', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=7, leading=9, textColor=colors.HexColor("#1d4ed8"))
            badge_pass = ParagraphStyle('BP', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=7, leading=9, textColor=colors.HexColor("#15803d"))

            story = []

            # Page 1: Title & Summary
            story.append(Paragraph("WEBSITE TECHNICAL & CYBERSECURITY AUDIT REPORT", title_style))
            story.append(Paragraph(f"<b>Target Domain:</b> {self.target_url} &nbsp;|&nbsp; <b>Inspection Date:</b> {datetime.now().strftime('%B %d, %Y')} &nbsp;|&nbsp; <b>Engine:</b> InersiaLab Security Suite", subtitle_style))
            story.append(HRFlowable(width="100%", thickness=1.2, color=colors.HexColor("#111827"), spaceBefore=0, spaceAfter=8))

            server_str = f"{headers_info.get('server') or 'Standard Web Server'}"
            if headers_info.get("powered_by"):
                server_str += f" / {headers_info.get('powered_by')}"

            summary_data = [
                [
                    Paragraph(f"<b>Target Host & IP</b><br/>{self.domain} ({ip_address})", body_style),
                    Paragraph(f"<b>Detected Web Server</b><br/>{server_str}", body_style),
                    Paragraph(f"<b>Overall Security Posture</b><br/><font color='#dc2626'><b>GRADE: {grade}</b></font>", body_style),
                ],
                [
                    Paragraph(f"<b>Critical Flaws:</b> <font color='#991b1b'><b>{counts['critical']} Defects</b></font>", body_style),
                    Paragraph(f"<b>High / Medium Flaws:</b> <font color='#c2410c'><b>{counts['high']} High</b></font> | <font color='#b45309'><b>{counts['medium']} Medium</b></font>", body_style),
                    Paragraph(f"<b>Operational / Passed:</b> {counts['low']} Low | <font color='#15803d'><b>{counts['passed']} Passed</b></font>", body_style),
                ]
            ]
            sum_table = Table(summary_data, colWidths=[174, 175, 174])
            sum_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#f9fafb")),
                ('BOX', (0, 0), (-1, -1), 1, colors.HexColor("#d1d5db")),
                ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#e5e7eb")),
                ('TOPPADDING', (0, 0), (-1, -1), 4),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
                ('LEFTPADDING', (0, 0), (-1, -1), 7),
                ('RIGHTPADDING', (0, 0), (-1, -1), 7),
            ]))
            story.append(sum_table)
            story.append(Spacer(1, 8))

            story.append(Paragraph("1. Executive Summary & Severity Matrix", h1_style))

            matrix_data = [
                [Paragraph("<b>Sev</b>", body_bold), Paragraph("<b>Vulnerability / Defect</b>", body_bold), Paragraph("<b>Location</b>", body_bold), Paragraph("<b>Technical Impact & Threat Vector</b>", body_bold)]
            ]

            badge_map = {"critical": badge_crit, "high": badge_high, "medium": badge_med, "low": badge_low, "passed": badge_pass}
            sev_order = {"critical": 0, "high": 1, "medium": 2, "low": 3, "passed": 4}
            sorted_findings = sorted(self.findings, key=lambda x: sev_order.get(x["severity"], 5))

            import html

            for f in sorted_findings:
                s_badge = badge_map.get(f["severity"], body_bold)
                matrix_data.append([
                    Paragraph(f["severity"][:4].upper(), s_badge),
                    Paragraph(f"<b>{html.escape(f['title'])}</b>", body_style),
                    Paragraph(html.escape(f["location"]).replace("\n", "<br/>"), body_style),
                    Paragraph(html.escape(f["impact"]).replace("\n", "<br/>"), body_style),
                ])

            matrix_table = Table(matrix_data, colWidths=[40, 155, 118, 210])
            matrix_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#111827")),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#d1d5db")),
                ('TOPPADDING', (0, 0), (-1, -1), 2.5),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 2.5),
                ('LEFTPADDING', (0, 0), (-1, -1), 5),
                ('RIGHTPADDING', (0, 0), (-1, -1), 5),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#f9fafb")]),
            ]))
            story.append(matrix_table)

            story.append(PageBreak())

            # Page 2: .htaccess
            story.append(Paragraph("2. Detailed Technical Remediation Guide", h1_style))
            story.append(Paragraph("Step 2.1: Server Hardening via .htaccess", h2_style))
            story.append(Paragraph("Insert the following block at the top of your root <code>.htaccess</code> file:", body_style))
            story.append(Spacer(1, 3))
            c_ht = Table([[Paragraph(html.escape(patches["htaccess"]).replace("\n", "<br/>").replace(" ", "&nbsp;"), code_style)]], colWidths=[523])
            c_ht.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#f3f4f6")),
                ('BOX', (0, 0), (-1, -1), 1, colors.HexColor("#9ca3af")),
                ('TOPPADDING', (0, 0), (-1, -1), 5),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
                ('LEFTPADDING', (0, 0), (-1, -1), 7),
                ('RIGHTPADDING', (0, 0), (-1, -1), 7),
            ]))
            story.append(c_ht)

            story.append(PageBreak())

            # Page 3: functions.php
            story.append(Paragraph("Step 2.2: Application Security Patch (functions.php)", h2_style))
            story.append(Paragraph("Add this snippet to your child theme's <code>functions.php</code> or via Code Snippets:", body_style))
            story.append(Spacer(1, 3))
            c_fn = Table([[Paragraph(html.escape(patches["functions_php"]).replace("\n", "<br/>").replace(" ", "&nbsp;"), code_style)]], colWidths=[523])
            c_fn.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#f3f4f6")),
                ('BOX', (0, 0), (-1, -1), 1, colors.HexColor("#9ca3af")),
                ('TOPPADDING', (0, 0), (-1, -1), 5),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
                ('LEFTPADDING', (0, 0), (-1, -1), 7),
                ('RIGHTPADDING', (0, 0), (-1, -1), 7),
            ]))
            story.append(c_fn)

            story.append(PageBreak())

            # Page 4: Form & DNS
            story.append(Paragraph("Step 2.3: Contact Form Security & PII Protection", h2_style))
            story.append(Paragraph("Ensure form method is POST and submissions are dispatched asynchronously via AJAX:", body_style))
            story.append(Spacer(1, 3))
            c_fm = Table([[Paragraph(html.escape(patches["contact_form"]).replace("\n", "<br/>").replace(" ", "&nbsp;"), code_style)]], colWidths=[523])
            c_fm.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#f3f4f6")),
                ('BOX', (0, 0), (-1, -1), 1, colors.HexColor("#9ca3af")),
                ('TOPPADDING', (0, 0), (-1, -1), 5),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
                ('LEFTPADDING', (0, 0), (-1, -1), 7),
                ('RIGHTPADDING', (0, 0), (-1, -1), 7),
            ]))
            story.append(c_fm)
            story.append(Spacer(1, 8))

            story.append(Paragraph("Step 2.4: Email Anti-Spoofing & DNS Hardening", h2_style))
            dns_table_data = [
                [Paragraph("<b>Record Type</b>", body_bold), Paragraph("<b>Host / Name</b>", body_bold), Paragraph("<b>Target / Value</b>", body_bold), Paragraph("<b>Security Protection</b>", body_bold)]
            ]
            for d in patches["dns"]:
                dns_table_data.append([
                    Paragraph(html.escape(d["type"]), body_style),
                    Paragraph(html.escape(d["host"]), body_style),
                    Paragraph(f"<code>{html.escape(d['value']).replace(chr(10), '<br/>')}</code>", code_style),
                    Paragraph(html.escape(d["purpose"]), body_style),
                ])
            dns_tbl = Table(dns_table_data, colWidths=[55, 55, 270, 143])
            dns_tbl.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#e5e7eb")),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#d1d5db")),
                ('TOPPADDING', (0, 0), (-1, -1), 4),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
                ('LEFTPADDING', (0, 0), (-1, -1), 6),
                ('RIGHTPADDING', (0, 0), (-1, -1), 6),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ]))
            story.append(dns_tbl)

            story.append(PageBreak())

            # Page 5: Master AI Fix Prompt
            story.append(Paragraph("3. Master AI Fix Prompt (Direct Copy & Paste)", h1_style))
            story.append(Paragraph("Paste the prompt below into an AI assistant or deliver it to your development team:", body_style))
            story.append(Spacer(1, 6))
            c_prm = Table([[Paragraph(html.escape(patches["master_prompt"]).replace("\n", "<br/>").replace(" ", "&nbsp;"), code_style)]], colWidths=[523])
            c_prm.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#1e293b")),
                ('BOX', (0, 0), (-1, -1), 1, colors.HexColor("#0f172a")),
                ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
                ('TOPPADDING', (0, 0), (-1, -1), 7),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 7),
                ('LEFTPADDING', (0, 0), (-1, -1), 9),
                ('RIGHTPADDING', (0, 0), (-1, -1), 9),
            ]))
            story.append(c_prm)

            doc.build(story, canvasmaker=NumberedCanvas)
            return pdf_path, pdf_filename
        except Exception as e:
            self.log(f"    PDF build error: {e}")
            return None, None


def run_security_audit(target_url: str, log_callback=None) -> dict:
    runner = SecurityAuditRunner(target_url, log_callback=log_callback)
    return runner.run()


if __name__ == "__main__":
    target = sys.argv[1] if len(sys.argv) > 1 else "https://inersialab.com"
    res = run_security_audit(target, log_callback=print)
    print("\nResult summary:", res["counts"])